-- Company Skill Intelligence: canonical company identity and point-in-time skill facts.
BEGIN;

CREATE TABLE IF NOT EXISTS public.companies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_key   TEXT NOT NULL UNIQUE,
    canonical_name  TEXT NOT NULL UNIQUE,
    slug            TEXT NOT NULL UNIQUE,
    industry        TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.company_aliases (
    alias_key       TEXT PRIMARY KEY,
    alias_name      TEXT NOT NULL,
    company_id      BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    source          TEXT NOT NULL DEFAULT 'jobs_backfill',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.jobs
    ADD COLUMN IF NOT EXISTS company_id BIGINT
        REFERENCES public.companies(id) ON DELETE SET NULL;
ALTER TABLE public.job_source_runs
    ADD COLUMN IF NOT EXISTS company_id BIGINT
        REFERENCES public.companies(id) ON DELETE SET NULL;

WITH normalized AS (
    SELECT
        company_name,
        COALESCE(
            NULLIF(LOWER(REGEXP_REPLACE(BTRIM(company_name), '[^a-z0-9]+', '', 'g')), ''),
            'company' || MD5(BTRIM(company_name))
        ) AS canonical_key
    FROM public.jobs
    WHERE NULLIF(BTRIM(company_name), '') IS NOT NULL
), representatives AS (
    SELECT canonical_key, MIN(company_name) AS canonical_name
    FROM normalized
    GROUP BY canonical_key
)
INSERT INTO public.companies (canonical_key, canonical_name, slug)
SELECT canonical_key, canonical_name, canonical_key
FROM representatives
ON CONFLICT (canonical_key) DO NOTHING;

INSERT INTO public.company_aliases (alias_key, alias_name, company_id)
SELECT DISTINCT
    LOWER(REGEXP_REPLACE(BTRIM(j.company_name), '\s+', ' ', 'g')),
    j.company_name,
    c.id
FROM public.jobs j
JOIN public.companies c
  ON c.canonical_key = COALESCE(
      NULLIF(LOWER(REGEXP_REPLACE(BTRIM(j.company_name), '[^a-z0-9]+', '', 'g')), ''),
      'company' || MD5(BTRIM(j.company_name))
  )
WHERE NULLIF(BTRIM(j.company_name), '') IS NOT NULL
ON CONFLICT (alias_key) DO NOTHING;

UPDATE public.jobs j
SET company_id = ca.company_id
FROM public.company_aliases ca
WHERE ca.alias_key = LOWER(REGEXP_REPLACE(BTRIM(j.company_name), '\s+', ' ', 'g'))
  AND j.company_id IS DISTINCT FROM ca.company_id;

UPDATE public.job_source_runs jsr
SET company_id = ca.company_id
FROM public.company_aliases ca
WHERE ca.alias_key = LOWER(REGEXP_REPLACE(BTRIM(jsr.company_name), '\s+', ' ', 'g'))
  AND jsr.company_id IS DISTINCT FROM ca.company_id;

CREATE INDEX IF NOT EXISTS idx_jobs_company_id ON public.jobs (company_id);
CREATE INDEX IF NOT EXISTS idx_job_source_runs_company_id
    ON public.job_source_runs (company_id, completed_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_aliases_company_id
    ON public.company_aliases (company_id);

CREATE TABLE IF NOT EXISTS public.company_skill_run_facts (
    source_run_id          UUID NOT NULL
                           REFERENCES public.job_source_runs(id) ON DELETE CASCADE,
    company_id             BIGINT NOT NULL
                           REFERENCES public.companies(id) ON DELETE CASCADE,
    skill_id               INTEGER NOT NULL
                           REFERENCES public.skills(id) ON DELETE RESTRICT,
    active_job_count       INTEGER NOT NULL CHECK (active_job_count >= 0),
    primary_job_count      INTEGER NOT NULL CHECK (
                               primary_job_count >= 0
                               AND primary_job_count <= active_job_count
                           ),
    average_required_level NUMERIC(4, 2) CHECK (
                               average_required_level IS NULL
                               OR average_required_level BETWEEN 0 AND 5
                           ),
    required_level_counts  JSONB NOT NULL DEFAULT '{}'::JSONB,
    role_domain_counts     JSONB NOT NULL DEFAULT '{}'::JSONB,
    location_counts        JSONB NOT NULL DEFAULT '{}'::JSONB,
    observed_at            TIMESTAMPTZ NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (source_run_id, company_id, skill_id)
);

CREATE INDEX IF NOT EXISTS idx_company_skill_run_facts_company_observed
    ON public.company_skill_run_facts (company_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_skill_run_facts_skill_observed
    ON public.company_skill_run_facts (skill_id, observed_at DESC);

CREATE TABLE IF NOT EXISTS public.company_skill_profiles (
    company_id                 BIGINT NOT NULL
                               REFERENCES public.companies(id) ON DELETE CASCADE,
    skill_id                   INTEGER NOT NULL
                               REFERENCES public.skills(id) ON DELETE RESTRICT,
    first_seen_at              TIMESTAMPTZ NOT NULL,
    last_seen_at               TIMESTAMPTZ NOT NULL,
    latest_job_count           INTEGER NOT NULL DEFAULT 0 CHECK (latest_job_count >= 0),
    latest_primary_job_count   INTEGER NOT NULL DEFAULT 0
                               CHECK (latest_primary_job_count >= 0),
    peak_job_count             INTEGER NOT NULL DEFAULT 0 CHECK (peak_job_count >= 0),
    observation_run_count      INTEGER NOT NULL DEFAULT 0
                               CHECK (observation_run_count >= 0),
    average_required_level     NUMERIC(4, 2),
    trend_direction            TEXT NOT NULL DEFAULT 'steady'
                               CHECK (trend_direction IN (
                                   'emerging', 'steady', 'declining', 'dormant'
                               )),
    latest_source_run_id       UUID REFERENCES public.job_source_runs(id) ON DELETE SET NULL,
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (company_id, skill_id)
);

CREATE INDEX IF NOT EXISTS idx_company_skill_profiles_company_demand
    ON public.company_skill_profiles (
        company_id, latest_job_count DESC, latest_primary_job_count DESC
    );
CREATE INDEX IF NOT EXISTS idx_company_skill_profiles_skill_demand
    ON public.company_skill_profiles (skill_id, latest_job_count DESC);

CREATE OR REPLACE FUNCTION public.resolve_company_entity(p_company_name TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_alias_key TEXT;
    v_canonical_key TEXT;
    v_company_id BIGINT;
BEGIN
    IF NULLIF(BTRIM(p_company_name), '') IS NULL THEN
        RAISE EXCEPTION 'company name is required';
    END IF;
    v_alias_key := LOWER(REGEXP_REPLACE(BTRIM(p_company_name), '\s+', ' ', 'g'));
    SELECT company_id INTO v_company_id
    FROM public.company_aliases WHERE alias_key = v_alias_key;
    IF v_company_id IS NOT NULL THEN
        RETURN v_company_id;
    END IF;

    v_canonical_key := COALESCE(
        NULLIF(LOWER(REGEXP_REPLACE(BTRIM(p_company_name), '[^a-z0-9]+', '', 'g')), ''),
        'company' || MD5(BTRIM(p_company_name))
    );
    INSERT INTO public.companies (canonical_key, canonical_name, slug)
    VALUES (v_canonical_key, BTRIM(p_company_name), v_canonical_key)
    ON CONFLICT (canonical_key) DO UPDATE SET updated_at = NOW()
    RETURNING id INTO v_company_id;
    INSERT INTO public.company_aliases (alias_key, alias_name, company_id, source)
    VALUES (v_alias_key, BTRIM(p_company_name), v_company_id, 'resolver')
    ON CONFLICT (alias_key) DO UPDATE SET company_id = EXCLUDED.company_id;
    RETURN v_company_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.refresh_company_skill_profiles(p_source_run_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_company_id BIGINT;
    v_rows INTEGER;
BEGIN
    SELECT company_id INTO v_company_id
    FROM public.job_source_runs
    WHERE id = p_source_run_id AND status = 'complete';
    IF v_company_id IS NULL THEN
        RAISE EXCEPTION 'complete source run with company_id is required';
    END IF;

    WITH ranked AS (
        SELECT f.*,
               ROW_NUMBER() OVER (
                   PARTITION BY f.company_id, f.skill_id
                   ORDER BY f.observed_at DESC, f.source_run_id DESC
               ) AS recency_rank
        FROM public.company_skill_run_facts f
        JOIN public.job_source_runs jsr ON jsr.id = f.source_run_id
        WHERE f.company_id = v_company_id AND jsr.status = 'complete'
    ), summary AS (
        SELECT
            company_id, skill_id,
            MIN(observed_at) AS first_seen_at,
            MAX(observed_at) AS last_seen_at,
            MAX(active_job_count) FILTER (WHERE recency_rank = 1) AS latest_job_count,
            MAX(active_job_count) FILTER (WHERE recency_rank = 2) AS previous_job_count,
            MAX(primary_job_count) FILTER (WHERE recency_rank = 1) AS latest_primary_job_count,
            MAX(active_job_count) AS peak_job_count,
            COUNT(DISTINCT source_run_id)::INTEGER AS observation_run_count,
            ROUND(
                SUM(COALESCE(average_required_level, 0) * active_job_count)
                / NULLIF(SUM(active_job_count), 0), 2
            ) AS average_required_level,
            (MAX(source_run_id::TEXT) FILTER (WHERE recency_rank = 1))::UUID
                AS latest_source_run_id
        FROM ranked GROUP BY company_id, skill_id
    )
    INSERT INTO public.company_skill_profiles (
        company_id, skill_id, first_seen_at, last_seen_at, latest_job_count,
        latest_primary_job_count, peak_job_count, observation_run_count,
        average_required_level, trend_direction, latest_source_run_id, updated_at
    )
    SELECT
        company_id, skill_id, first_seen_at, last_seen_at, latest_job_count,
        latest_primary_job_count, peak_job_count, observation_run_count,
        average_required_level,
        CASE
            WHEN latest_job_count = 0 THEN 'dormant'
            WHEN previous_job_count IS NULL THEN 'steady'
            WHEN latest_job_count >= previous_job_count * 1.25
             AND latest_job_count - previous_job_count >= 2 THEN 'emerging'
            WHEN latest_job_count <= previous_job_count * 0.75
             AND previous_job_count - latest_job_count >= 2 THEN 'declining'
            ELSE 'steady'
        END,
        latest_source_run_id, NOW()
    FROM summary
    ON CONFLICT (company_id, skill_id) DO UPDATE SET
        first_seen_at = EXCLUDED.first_seen_at,
        last_seen_at = EXCLUDED.last_seen_at,
        latest_job_count = EXCLUDED.latest_job_count,
        latest_primary_job_count = EXCLUDED.latest_primary_job_count,
        peak_job_count = EXCLUDED.peak_job_count,
        observation_run_count = EXCLUDED.observation_run_count,
        average_required_level = EXCLUDED.average_required_level,
        trend_direction = EXCLUDED.trend_direction,
        latest_source_run_id = EXCLUDED.latest_source_run_id,
        updated_at = NOW();
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    RETURN v_rows;
END;
$$;

REVOKE ALL ON FUNCTION public.resolve_company_entity(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.refresh_company_skill_profiles(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_company_entity(TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.refresh_company_skill_profiles(UUID) TO service_role;

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_skill_run_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_skill_profiles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.companies FROM anon, authenticated;
REVOKE ALL ON public.company_aliases FROM anon, authenticated;
REVOKE ALL ON public.company_skill_run_facts FROM anon, authenticated;
REVOKE ALL ON public.company_skill_profiles FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.companies TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.company_aliases TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.company_skill_run_facts TO service_role;
GRANT SELECT ON public.company_skill_profiles TO service_role;
GRANT INSERT, UPDATE ON public.company_skill_profiles TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.companies_id_seq TO service_role;

COMMENT ON TABLE public.company_skill_run_facts IS
    'Point-in-time company skill demand for one complete source run; zero rows retain dormancy.';
COMMENT ON TABLE public.company_skill_profiles IS
    'Historical and latest company skill demand derived only from complete source runs.';

NOTIFY pgrst, 'reload schema';
COMMIT;
