-- Job Intelligence: append-only structured feedback.

CREATE TABLE IF NOT EXISTS public.job_feedback_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_event_id UUID NOT NULL,
    job_id          TEXT NOT NULL REFERENCES public.jobs(job_id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    feedback_kind   TEXT NOT NULL
                    CHECK (feedback_kind IN ('personal', 'quality')),
    reason_code     TEXT NOT NULL,
    surface         TEXT NOT NULL
                    CHECK (surface IN ('dashboard', 'market', 'job_detail', 'other')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, client_event_id),
    CHECK (
        (
            feedback_kind = 'personal'
            AND reason_code IN (
                'not_my_role', 'location', 'seniority', 'compensation',
                'company', 'skills_gap', 'already_applied'
            )
        )
        OR
        (
            feedback_kind = 'quality'
            AND reason_code IN (
                'looks_old', 'apply_link_closed', 'duplicate',
                'details_wrong', 'posting_inactive'
            )
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_job_feedback_events_user_created
    ON public.job_feedback_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_job_feedback_events_job_quality
    ON public.job_feedback_events (job_id, feedback_kind, reason_code);

ALTER TABLE public.job_feedback_events ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY job_feedback_events_own_select
        ON public.job_feedback_events
        FOR SELECT
        USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY job_feedback_events_own_insert
        ON public.job_feedback_events
        FOR INSERT
        WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT SELECT, INSERT ON public.job_feedback_events TO authenticated;

COMMENT ON TABLE public.job_feedback_events IS
    'Append-only personal-fit and shared listing-quality feedback.';

NOTIFY pgrst, 'reload schema';
