-- Job Intelligence: append-only structured feedback.
CREATE TABLE IF NOT EXISTS public.job_feedback_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_event_id UUID NOT NULL,
    job_id          TEXT NOT NULL REFERENCES public.jobs(job_id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    feedback_kind   TEXT NOT NULL
                    CHECK (feedback_kind IN ('personal', 'quality')),
    reason_code     TEXT NOT NULL,
    surface         TEXT NOT NULL
                    CHECK (surface IN ('dashboard', 'market', 'job_detail', 'other')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, client_event_id),
    CHECK (
        (
            feedback_kind = 'personal'
            AND reason_code IN (
                'not_my_role', 'location', 'seniority', 'compensation',
                'company', 'skills_gap', 'already_applied'
            )
        )
        OR
        (
            feedback_kind = 'quality'
            AND reason_code IN (
                'looks_old', 'apply_link_closed', 'duplicate',
                'details_wrong', 'posting_inactive'
            )
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_job_feedback_events_user_created
    ON public.job_feedback_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_job_feedback_events_job_quality
    ON public.job_feedback_events (job_id, feedback_kind, reason_code);

ALTER TABLE public.job_feedback_events ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY job_feedback_events_own_select
        ON public.job_feedback_events
        FOR SELECT
        USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY job_feedback_events_own_insert
        ON public.job_feedback_events
        FOR INSERT
        WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT SELECT, INSERT ON public.job_feedback_events TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.job_feedback_events_id_seq TO authenticated, service_role;
COMMENT ON TABLE public.job_feedback_events IS
    'Append-only personal-fit and shared listing-quality feedback.';
CREATE TABLE IF NOT EXISTS public.job_intelligence_snapshots (
    job_id                    TEXT PRIMARY KEY REFERENCES public.jobs(job_id) ON DELETE CASCADE,
    tracking_count            INTEGER NOT NULL DEFAULT 0,
    applied_count             INTEGER NOT NULL DEFAULT 0,
    outcome_count             INTEGER NOT NULL DEFAULT 0,
    responded_count           INTEGER NOT NULL DEFAULT 0,
    ghosted_count             INTEGER NOT NULL DEFAULT 0,
    interviewed_count         INTEGER NOT NULL DEFAULT 0,
    offer_count               INTEGER NOT NULL DEFAULT 0,
    quality_report_count      INTEGER NOT NULL DEFAULT 0,
    looks_old_count           INTEGER NOT NULL DEFAULT 0,
    apply_link_closed_count   INTEGER NOT NULL DEFAULT 0,
    posting_inactive_count    INTEGER NOT NULL DEFAULT 0,
    duplicate_report_count    INTEGER NOT NULL DEFAULT 0,
    details_wrong_count       INTEGER NOT NULL DEFAULT 0,
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.job_intelligence_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.job_intelligence_snapshots FROM anon, authenticated;
GRANT SELECT ON public.job_intelligence_snapshots TO service_role;
CREATE INDEX IF NOT EXISTS idx_job_applications_job_status
    ON public.job_applications (job_id, status);

CREATE SCHEMA IF NOT EXISTS private;
CREATE OR REPLACE FUNCTION private.refresh_job_intelligence_snapshot(
    p_job_id TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    INSERT INTO public.job_intelligence_snapshots (
        job_id,
        tracking_count,
        applied_count,
        outcome_count,
        responded_count,
        ghosted_count,
        interviewed_count,
        offer_count,
        quality_report_count,
        looks_old_count,
        apply_link_closed_count,
        posting_inactive_count,
        duplicate_report_count,
        details_wrong_count,
        updated_at
    )
    WITH application_counts AS (
        SELECT
            COUNT(*) FILTER (
                WHERE status IN (
                    'saved', 'applied', 'screening', 'interviewing', 'final_round'
                )
            )::INTEGER AS tracking_count,
            COUNT(*) FILTER (
                WHERE status IN (
                    'applied', 'screening', 'interviewing', 'final_round',
                    'ghosted', 'rejected', 'offer'
                )
            )::INTEGER AS applied_count,
            COUNT(*) FILTER (
                WHERE status IN ('ghosted', 'rejected', 'offer', 'withdrew')
            )::INTEGER AS outcome_count,
            COUNT(*) FILTER (
                WHERE status IN (
                    'screening', 'interviewing', 'final_round', 'rejected', 'offer'
                )
            )::INTEGER AS responded_count,
            COUNT(*) FILTER (WHERE status = 'ghosted')::INTEGER AS ghosted_count,
            COUNT(*) FILTER (
                WHERE status IN ('interviewing', 'final_round', 'offer')
            )::INTEGER AS interviewed_count,
            COUNT(*) FILTER (WHERE status = 'offer')::INTEGER AS offer_count
        FROM public.job_applications
        WHERE job_id = p_job_id
    ),
    feedback_counts AS (
        SELECT
            COUNT(DISTINCT user_id) FILTER (
                WHERE feedback_kind = 'quality'
            )::INTEGER AS quality_report_count,
            COUNT(DISTINCT user_id) FILTER (
                WHERE feedback_kind = 'quality' AND reason_code = 'looks_old'
            )::INTEGER AS looks_old_count,
            COUNT(DISTINCT user_id) FILTER (
                WHERE feedback_kind = 'quality'
                  AND reason_code = 'apply_link_closed'
            )::INTEGER AS apply_link_closed_count,
            COUNT(DISTINCT user_id) FILTER (
                WHERE feedback_kind = 'quality'
                  AND reason_code = 'posting_inactive'
            )::INTEGER AS posting_inactive_count,
            COUNT(DISTINCT user_id) FILTER (
                WHERE feedback_kind = 'quality' AND reason_code = 'duplicate'
            )::INTEGER AS duplicate_report_count,
            COUNT(DISTINCT user_id) FILTER (
                WHERE feedback_kind = 'quality' AND reason_code = 'details_wrong'
            )::INTEGER AS details_wrong_count
        FROM public.job_feedback_events
        WHERE job_id = p_job_id
    )
    SELECT
        p_job_id,
        a.tracking_count,
        a.applied_count,
        a.outcome_count,
        a.responded_count,
        a.ghosted_count,
        a.interviewed_count,
        a.offer_count,
        f.quality_report_count,
        f.looks_old_count,
        f.apply_link_closed_count,
        f.posting_inactive_count,
        f.duplicate_report_count,
        f.details_wrong_count,
        NOW()
    FROM application_counts a
    CROSS JOIN feedback_counts f
    ON CONFLICT (job_id) DO UPDATE SET
        tracking_count = EXCLUDED.tracking_count,
        applied_count = EXCLUDED.applied_count,
        outcome_count = EXCLUDED.outcome_count,
        responded_count = EXCLUDED.responded_count,
        ghosted_count = EXCLUDED.ghosted_count,
        interviewed_count = EXCLUDED.interviewed_count,
        offer_count = EXCLUDED.offer_count,
        quality_report_count = EXCLUDED.quality_report_count,
        looks_old_count = EXCLUDED.looks_old_count,
        apply_link_closed_count = EXCLUDED.apply_link_closed_count,
        posting_inactive_count = EXCLUDED.posting_inactive_count,
        duplicate_report_count = EXCLUDED.duplicate_report_count,
        details_wrong_count = EXCLUDED.details_wrong_count,
        updated_at = NOW();
END;
$$;

REVOKE ALL ON FUNCTION private.refresh_job_intelligence_snapshot(TEXT)
    FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.refresh_job_intelligence_snapshot_trigger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    PERFORM private.refresh_job_intelligence_snapshot(
        CASE WHEN TG_OP = 'DELETE' THEN OLD.job_id ELSE NEW.job_id END
    );
    IF TG_OP = 'UPDATE' AND OLD.job_id IS DISTINCT FROM NEW.job_id THEN
        PERFORM private.refresh_job_intelligence_snapshot(OLD.job_id);
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.refresh_job_intelligence_snapshot_trigger()
    FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_refresh_job_intelligence_from_application
    ON public.job_applications;
CREATE TRIGGER trg_refresh_job_intelligence_from_application
AFTER INSERT OR UPDATE OF status, job_id OR DELETE
ON public.job_applications
FOR EACH ROW
EXECUTE FUNCTION private.refresh_job_intelligence_snapshot_trigger();

DROP TRIGGER IF EXISTS trg_refresh_job_intelligence_from_feedback
    ON public.job_feedback_events;
CREATE TRIGGER trg_refresh_job_intelligence_from_feedback
AFTER INSERT OR DELETE
ON public.job_feedback_events
FOR EACH ROW
EXECUTE FUNCTION private.refresh_job_intelligence_snapshot_trigger();

DO $$
BEGIN
    IF to_regclass('public.job_reports') IS NOT NULL THEN
        INSERT INTO public.job_feedback_events (
            client_event_id,
            job_id,
            user_id,
            feedback_kind,
            reason_code,
            surface,
            created_at
        )
        SELECT
            (
                SUBSTR(MD5('legacy-job-report:' || user_id || ':' || job_id), 1, 8)
                || '-' ||
                SUBSTR(MD5('legacy-job-report:' || user_id || ':' || job_id), 9, 4)
                || '-' ||
                SUBSTR(MD5('legacy-job-report:' || user_id || ':' || job_id), 13, 4)
                || '-' ||
                SUBSTR(MD5('legacy-job-report:' || user_id || ':' || job_id), 17, 4)
                || '-' ||
                SUBSTR(MD5('legacy-job-report:' || user_id || ':' || job_id), 21, 12)
            )::UUID,
            job_id,
            user_id,
            'quality',
            'posting_inactive',
            'other',
            reported_at
        FROM public.job_reports
        ON CONFLICT (user_id, client_event_id) DO NOTHING;

        EXECUTE 'DROP TRIGGER IF EXISTS trg_job_report_deactivation ON public.job_reports';
        EXECUTE 'REVOKE ALL ON public.job_reports FROM anon, authenticated';
    END IF;
END $$;

DROP FUNCTION IF EXISTS public.fn_job_report_deactivation();

DO $$
DECLARE
    affected RECORD;
BEGIN
    FOR affected IN
        SELECT DISTINCT job_id
        FROM (
            SELECT job_id FROM public.job_applications
            UNION
            SELECT job_id FROM public.job_feedback_events
        ) activity
    LOOP
        PERFORM private.refresh_job_intelligence_snapshot(affected.job_id);
    END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';
