-- 20260806c_partner_integrations.sql
-- Partner Integrations — the multi-tenant seam for B2B distribution partners
-- (first tenant: Finlatics). Built partner-generic on purpose: the second
-- partner must cost a row, not a release.
--
-- Six tables, three jobs:
--   identity   partners, partner_api_keys, partner_users
--   delivery   partner_webhooks, partner_webhook_deliveries
--   ledger     partner_job_deliveries
--
-- Security posture:
--   • API keys are stored HASHED (sha256). The raw key is shown once, at mint.
--     A DB leak must not yield a working credential.
--   • `partner_users.link_state` is the account-takeover gate. A partner key can
--     mint a sign-in link ONLY for an email that is new, or already linked to
--     that partner. An email that already belongs to an unlinked Myro account
--     goes to 'pending_verification' and the USER proves ownership by clicking a
--     magic link we send. Without this, one leaked partner key = session
--     minting for any Myro account whose email the attacker knows.
--   • RLS is enabled with NO policies on every table: these are service-role-only
--     surfaces. No end-user token ever reads them.
--
-- Additive + reversible: six new tables, nothing altered, no data touched.

-- ── identity ───────────────────────────────────────────────────────────────

create table if not exists public.partners (
    id          uuid primary key default gen_random_uuid(),
    slug        text not null unique,
    name        text not null,
    status      text not null default 'active' check (status in ('active', 'suspended')),
    created_at  timestamptz not null default now()
);

comment on table public.partners is
    'B2B distribution partners (Finlatics, colleges, …). One row per tenant.';

-- Raw keys are never stored. `key_prefix` is the non-secret, greppable half we
-- log and show in a dashboard; `key_hash` is sha256(full key). Lookup is by
-- prefix, then a constant-time compare on the hash.
create table if not exists public.partner_api_keys (
    id           uuid primary key default gen_random_uuid(),
    partner_id   uuid not null references public.partners(id) on delete cascade,
    key_prefix   text not null unique,
    key_hash     text not null,
    label        text,
    scopes       text[] not null default '{}',
    created_at   timestamptz not null default now(),
    last_used_at timestamptz,
    revoked_at   timestamptz
);

create index if not exists partner_api_keys_partner_live
    on public.partner_api_keys (partner_id)
    where revoked_at is null;

-- The partner's user ↔ our user. `external_id` is THEIR primary key; we never
-- assume their ids are emails or that emails are stable.
create table if not exists public.partner_users (
    id           uuid primary key default gen_random_uuid(),
    partner_id   uuid not null references public.partners(id) on delete cascade,
    external_id  text not null,
    email        text not null,
    user_id      uuid references auth.users(id) on delete set null,
    link_state   text not null default 'linked'
                 check (link_state in ('linked', 'pending_verification')),
    created_at   timestamptz not null default now(),
    linked_at    timestamptz,
    last_sso_at  timestamptz,
    unique (partner_id, external_id)
);

-- One Myro account maps to at most one seat per partner. Partial so the many
-- rows still awaiting verification (user_id null) don't collide.
create unique index if not exists partner_users_partner_user_uniq
    on public.partner_users (partner_id, user_id)
    where user_id is not null;

create index if not exists partner_users_email
    on public.partner_users (lower(email));

-- ── delivery ───────────────────────────────────────────────────────────────

-- One endpoint per partner in v1. `signing_secret` is the shared HMAC secret the
-- partner verifies with; generated by us, shown once, rotatable by replacing the
-- row. It is a signing secret, not a credential into Myro — worst case on leak
-- is a forged payload TO the partner, not access to us.
create table if not exists public.partner_webhooks (
    id                   uuid primary key default gen_random_uuid(),
    partner_id           uuid not null unique references public.partners(id) on delete cascade,
    url                  text not null,
    signing_secret       text not null,
    event_types          text[] not null default array['job_matches.new'],
    status               text not null default 'active' check (status in ('active', 'paused')),
    consecutive_failures integer not null default 0,
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now(),
    last_delivery_at     timestamptz
);

-- Every attempt is on the record. `event_id` is the idempotency key we send in
-- the payload and the header, so a partner can dedupe our retries.
create table if not exists public.partner_webhook_deliveries (
    id              uuid primary key default gen_random_uuid(),
    event_id        text not null unique,
    partner_id      uuid not null references public.partners(id) on delete cascade,
    event_type      text not null,
    url             text not null,
    payload         jsonb not null,
    status          text not null default 'pending'
                    check (status in ('pending', 'delivered', 'failed')),
    attempts        integer not null default 0,
    response_code   integer,
    error           text,
    created_at      timestamptz not null default now(),
    next_attempt_at timestamptz,
    delivered_at    timestamptz
);

create index if not exists partner_webhook_deliveries_pending
    on public.partner_webhook_deliveries (next_attempt_at)
    where status = 'pending';

create index if not exists partner_webhook_deliveries_partner_recent
    on public.partner_webhook_deliveries (partner_id, created_at desc);

-- ── ledger ─────────────────────────────────────────────────────────────────

-- What we have already told this partner about this user. A ledger, not a
-- timestamp window: "jobs since T" repeats itself the moment a clock, a backfill
-- or a retry disagrees, and the partner's user gets the same opening twice.
create table if not exists public.partner_job_deliveries (
    partner_user_id uuid not null references public.partner_users(id) on delete cascade,
    job_id          text not null,
    delivered_at    timestamptz not null default now(),
    primary key (partner_user_id, job_id)
);

-- ── RLS: service-role only, no policies ────────────────────────────────────

alter table public.partners                   enable row level security;
alter table public.partner_api_keys           enable row level security;
alter table public.partner_users              enable row level security;
alter table public.partner_webhooks           enable row level security;
alter table public.partner_webhook_deliveries enable row level security;
alter table public.partner_job_deliveries     enable row level security;

notify pgrst, 'reload schema';
