-- Trusted Job Lifecycle: durable source evidence, listing observations, and exposures.
BEGIN;

ALTER TABLE public.jobs
    ADD COLUMN IF NOT EXISTS listing_confidence TEXT NOT NULL DEFAULT 'uncertain'
        CHECK (listing_confidence IN ('active', 'uncertain', 'likely_closed', 'closed')),
    ADD COLUMN IF NOT EXISTS last_verified_live_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_verification_attempt_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS consecutive_complete_misses INTEGER NOT NULL DEFAULT 0
        CHECK (consecutive_complete_misses >= 0),
    ADD COLUMN IF NOT EXISTS confidence_reason TEXT,
    ADD COLUMN IF NOT EXISTS quarantined_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deletion_eligible_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS retired_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS reactivated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS lifecycle_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE public.jobs
SET
    listing_confidence = CASE
        WHEN is_active IS NOT TRUE THEN 'closed'
        WHEN last_seen IS NULL THEN 'uncertain'
        WHEN last_seen >= TO_CHAR(CURRENT_DATE - 21, 'YYYYMMDD')::INTEGER THEN 'active'
        ELSE 'uncertain'
    END,
    last_verified_live_at = CASE
        WHEN is_active IS TRUE
         AND last_seen BETWEEN 20000101 AND 29991231
        THEN TO_DATE(last_seen::TEXT, 'YYYYMMDD')::TIMESTAMP AT TIME ZONE 'UTC'
        ELSE last_verified_live_at
    END,
    confidence_reason = CASE
        WHEN is_active IS NOT TRUE THEN 'legacy_inactive'
        WHEN last_seen IS NULL THEN 'missing_last_seen'
        WHEN last_seen >= TO_CHAR(CURRENT_DATE - 21, 'YYYYMMDD')::INTEGER
            THEN 'recent_scraper_observation'
        ELSE 'stale_scraper_observation'
    END,
    lifecycle_updated_at = NOW();

CREATE INDEX IF NOT EXISTS idx_jobs_listing_confidence
    ON public.jobs (listing_confidence, last_verified_live_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_deletion_eligible
    ON public.jobs (deletion_eligible_at)
    WHERE deletion_eligible_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.job_source_runs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    feed_run_id         UUID NOT NULL,
    company_name        TEXT NOT NULL,
    source_key          TEXT NOT NULL,
    provider            TEXT NOT NULL,
    started_at          TIMESTAMPTZ NOT NULL,
    completed_at        TIMESTAMPTZ,
    status              TEXT NOT NULL
                        CHECK (status IN ('complete', 'partial', 'failed', 'blocked')),
    observed_count      INTEGER NOT NULL DEFAULT 0 CHECK (observed_count >= 0),
    prior_good_count    INTEGER CHECK (prior_good_count IS NULL OR prior_good_count >= 0),
    coverage_ratio      NUMERIC(7, 6)
                        CHECK (coverage_ratio IS NULL OR coverage_ratio BETWEEN 0 AND 1),
    run_marker          INTEGER,
    parser_version      TEXT,
    failure_reason      TEXT,
    metadata            JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (feed_run_id, company_name, source_key)
);

CREATE INDEX IF NOT EXISTS idx_job_source_runs_company_completed
    ON public.job_source_runs (company_name, completed_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_source_runs_status_completed
    ON public.job_source_runs (status, completed_at DESC);

CREATE TABLE IF NOT EXISTS public.job_listing_observations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              TEXT NOT NULL,
    user_id             UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    source_run_id       UUID REFERENCES public.job_source_runs(id) ON DELETE SET NULL,
    client_event_id     UUID,
    observer            TEXT NOT NULL
                        CHECK (observer IN ('scraper', 'verifier', 'user', 'operator')),
    result              TEXT NOT NULL CHECK (result IN (
                            'seen_live', 'apply_live', 'source_missing', 'closed',
                            'redirected', 'wrong_role', 'blocked', 'timeout', 'error'
                        )),
    strength            TEXT NOT NULL CHECK (strength IN ('strong', 'medium', 'weak')),
    observed_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    evidence            JSONB NOT NULL DEFAULT '{}'::JSONB,
    verifier_version    TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, client_event_id)
);

CREATE INDEX IF NOT EXISTS idx_job_listing_observations_job_observed
    ON public.job_listing_observations (job_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_listing_observations_result_observed
    ON public.job_listing_observations (result, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_listing_observations_source_run
    ON public.job_listing_observations (source_run_id)
    WHERE source_run_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.job_recommendation_exposures (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    job_id              TEXT NOT NULL,
    surface             TEXT NOT NULL CHECK (surface IN (
                            'dashboard', 'market', 'collections', 'agent_pick',
                            'notification', 'other'
                        )),
    shown_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confidence_at_show  TEXT NOT NULL CHECK (confidence_at_show IN (
                            'active', 'uncertain', 'likely_closed', 'closed'
                        )),
    verified_live_at    TIMESTAMPTZ,
    feed_version        TEXT,
    match_id            INTEGER REFERENCES public.user_job_matches(id) ON DELETE SET NULL,
    metadata            JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS idx_job_recommendation_exposures_user_shown
    ON public.job_recommendation_exposures (user_id, shown_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_recommendation_exposures_job_shown
    ON public.job_recommendation_exposures (job_id, shown_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_recommendation_exposures_shown_at
    ON public.job_recommendation_exposures (shown_at);

ALTER TABLE public.job_feedback_events
    DROP CONSTRAINT IF EXISTS job_feedback_events_check;
ALTER TABLE public.job_feedback_events
    ADD CONSTRAINT job_feedback_events_check CHECK (
        (feedback_kind = 'personal' AND reason_code IN (
            'not_my_role', 'location', 'seniority', 'compensation',
            'company', 'skills_gap', 'already_applied'
        ))
        OR
        (feedback_kind = 'quality' AND reason_code IN (
            'looks_old', 'apply_link_closed', 'apply_link_live',
            'apply_redirected', 'apply_wrong_role', 'apply_technical_error',
            'duplicate', 'details_wrong', 'posting_inactive'
        ))
    );

CREATE SCHEMA IF NOT EXISTS private;
CREATE OR REPLACE FUNCTION private.capture_job_feedback_observation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    observation_result TEXT;
    observation_strength TEXT;
BEGIN
    IF NEW.feedback_kind <> 'quality' OR NEW.reason_code NOT IN (
        'apply_link_closed', 'apply_link_live', 'apply_redirected',
        'apply_wrong_role', 'apply_technical_error', 'posting_inactive'
    ) THEN
        RETURN NEW;
    END IF;

    observation_result := CASE NEW.reason_code
        WHEN 'apply_link_live' THEN 'apply_live'
        WHEN 'apply_link_closed' THEN 'closed'
        WHEN 'posting_inactive' THEN 'closed'
        WHEN 'apply_redirected' THEN 'redirected'
        WHEN 'apply_wrong_role' THEN 'wrong_role'
        ELSE 'error'
    END;
    observation_strength := CASE
        WHEN observation_result IN ('apply_live', 'closed') THEN 'strong'
        WHEN observation_result IN ('redirected', 'wrong_role') THEN 'medium'
        ELSE 'weak'
    END;

    INSERT INTO public.job_listing_observations (
        job_id, user_id, client_event_id, observer, result, strength,
        observed_at, evidence, verifier_version
    ) VALUES (
        NEW.job_id, NEW.user_id, NEW.client_event_id, 'user',
        observation_result, observation_strength, NEW.created_at,
        jsonb_build_object('surface', NEW.surface, 'feedback_event_id', NEW.id),
        'feedback-v1'
    ) ON CONFLICT (user_id, client_event_id) DO NOTHING;

    IF observation_result = 'apply_live' THEN
        UPDATE public.jobs SET
            listing_confidence = 'active',
            last_verified_live_at = GREATEST(last_verified_live_at, NEW.created_at),
            last_verification_attempt_at = NEW.created_at,
            consecutive_complete_misses = 0,
            confidence_reason = 'user_confirmed_live',
            quarantined_at = NULL,
            deletion_eligible_at = NULL,
            retired_at = NULL,
            reactivated_at = CASE
                WHEN listing_confidence IN ('likely_closed', 'closed') THEN NEW.created_at
                ELSE reactivated_at
            END,
            is_active = TRUE,
            lifecycle_updated_at = NOW()
        WHERE job_id = NEW.job_id;
    ELSE
        UPDATE public.jobs SET
            listing_confidence = CASE
                WHEN listing_confidence IN ('likely_closed', 'closed')
                    THEN listing_confidence
                ELSE 'uncertain'
            END,
            last_verification_attempt_at = NEW.created_at,
            confidence_reason = 'user_' || observation_result,
            lifecycle_updated_at = NOW()
        WHERE job_id = NEW.job_id;
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.capture_job_feedback_observation() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS trg_capture_job_feedback_observation ON public.job_feedback_events;
CREATE TRIGGER trg_capture_job_feedback_observation
AFTER INSERT ON public.job_feedback_events
FOR EACH ROW EXECUTE FUNCTION private.capture_job_feedback_observation();

INSERT INTO public.job_listing_observations (
    job_id, user_id, client_event_id, observer, result, strength,
    observed_at, evidence, verifier_version
)
SELECT
    job_id, user_id, client_event_id, 'user',
    CASE WHEN reason_code IN ('apply_link_closed', 'posting_inactive')
        THEN 'closed' ELSE 'error' END,
    CASE WHEN reason_code IN ('apply_link_closed', 'posting_inactive')
        THEN 'strong' ELSE 'weak' END,
    created_at, jsonb_build_object('surface', surface, 'feedback_event_id', id),
    'feedback-backfill-v1'
FROM public.job_feedback_events
WHERE feedback_kind = 'quality'
  AND reason_code IN ('apply_link_closed', 'posting_inactive')
ON CONFLICT (user_id, client_event_id) DO NOTHING;

ALTER TABLE public.job_source_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_listing_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_recommendation_exposures ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.job_source_runs FROM anon, authenticated;
REVOKE ALL ON public.job_listing_observations FROM anon, authenticated;
REVOKE ALL ON public.job_recommendation_exposures FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON public.job_source_runs TO service_role;
GRANT SELECT, INSERT ON public.job_listing_observations TO service_role;
GRANT SELECT, INSERT, DELETE ON public.job_recommendation_exposures TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.job_listing_observations_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.job_recommendation_exposures_id_seq TO service_role;

COMMENT ON TABLE public.job_source_runs IS
    'Per-company source completeness; only complete runs may create absence evidence.';
COMMENT ON TABLE public.job_listing_observations IS
    'Append-only listing evidence retained after raw jobs are unloaded.';
COMMENT ON TABLE public.job_recommendation_exposures IS
    'Bounded audit trail of what listing confidence Myro showed a user.';

NOTIFY pgrst, 'reload schema';
COMMIT;
