-- Public GitHub repositories cited from roadmap topic pages.
-- Links only. The roadmap text stays on roadmap.sh; this table stores the
-- repository URL, the roadmap that cited it, the use case, and the Lightcast
-- skill it belongs to when that skill is one we already teach against.
-- Additive and reversible: drop table public.github_learning_repos.

begin;

create table if not exists public.github_learning_repos (
    id bigint generated always as identity primary key,
    owner text not null,
    name text not null,
    html_url text not null,
    roadmap_slug text not null,
    use_case text not null,
    taxonomy_key text,
    constraint github_learning_repos_use_case
        check (use_case in (
    'role_path',
    'language',
    'framework',
    'data_infrastructure',
    'practice',
    'ai_tooling'
        )),
    constraint github_learning_repos_repo_roadmap
        unique (owner, name, roadmap_slug)
);

comment on table public.github_learning_repos is
    'Repository links cited by a developer roadmap, joined to skills.taxonomy_key when the roadmap is that skill. No roadmap prose.';

create index if not exists github_learning_repos_taxonomy
    on public.github_learning_repos (taxonomy_key)
    where taxonomy_key is not null;

alter table public.github_learning_repos enable row level security;

drop policy if exists "learning repos are readable" on public.github_learning_repos;
create policy "learning repos are readable"
    on public.github_learning_repos for select
    to authenticated
    using (true);

revoke all on public.github_learning_repos from anon, authenticated;
grant select on public.github_learning_repos to authenticated;
grant all on public.github_learning_repos to service_role;

insert into public.github_learning_repos
    (owner, name, html_url, roadmap_slug, use_case, taxonomy_key)
values
  ('agno-agi', 'agno', 'https://github.com/agno-agi/agno', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('confident-ai', 'deepeval', 'https://github.com/confident-ai/deepeval', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('deepset-ai', 'haystack', 'https://github.com/deepset-ai/haystack', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('explodinggradients', 'ragas', 'https://github.com/explodinggradients/ragas', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('Helicone', 'helicone', 'https://github.com/Helicone/helicone', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('langchain-ai', 'langchain', 'https://github.com/langchain-ai/langchain', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('langchain-ai', 'langgraph', 'https://github.com/langchain-ai/langgraph', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('langfuse', 'langfuse', 'https://github.com/langfuse/langfuse', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('microsoft', 'autogen', 'https://github.com/microsoft/autogen', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('modelcontextprotocol', 'modelcontextprotocol', 'https://github.com/modelcontextprotocol/modelcontextprotocol', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('openai', 'openai-cookbook', 'https://github.com/openai/openai-cookbook', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('punkpeye', 'awesome-mcp-servers', 'https://github.com/punkpeye/awesome-mcp-servers', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('run-llama', 'llama_index', 'https://github.com/run-llama/llama_index', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('traceloop', 'openllmetry', 'https://github.com/traceloop/openllmetry', 'ai-agents', 'ai_tooling', 'AI Agents'),
  ('confident-ai', 'deepeval', 'https://github.com/confident-ai/deepeval', 'ai-engineer', 'role_path', null),
  ('deepset-ai', 'haystack', 'https://github.com/deepset-ai/haystack', 'ai-engineer', 'role_path', null),
  ('infiniflow', 'ragflow', 'https://github.com/infiniflow/ragflow', 'ai-engineer', 'role_path', null),
  ('lancedb', 'lancedb', 'https://github.com/lancedb/lancedb', 'ai-engineer', 'role_path', null),
  ('mind-network', 'Awesome-LLM-based-AI-Agents-Knowledge', 'https://github.com/mind-network/Awesome-LLM-based-AI-Agents-Knowledge', 'ai-engineer', 'role_path', null),
  ('openai', 'whisper', 'https://github.com/openai/whisper', 'ai-engineer', 'role_path', null),
  ('qdrant', 'qdrant', 'https://github.com/qdrant/qdrant', 'ai-engineer', 'role_path', null),
  ('vibrantlabsai', 'ragas', 'https://github.com/vibrantlabsai/ragas', 'ai-engineer', 'role_path', null),
  ('yunlong10', 'Awesome-LLMs-for-Video-Understanding', 'https://github.com/yunlong10/Awesome-LLMs-for-Video-Understanding', 'ai-engineer', 'role_path', null),
  ('mikeroyal', 'Azure-Guide', 'https://github.com/mikeroyal/Azure-Guide', 'ai-product-builder', 'role_path', null),
  ('Azure', 'PyRIT', 'https://github.com/Azure/PyRIT', 'ai-red-teaming', 'role_path', null),
  ('cysecbench', 'dataset', 'https://github.com/cysecbench/dataset', 'ai-red-teaming', 'role_path', null),
  ('apollographql', 'apollo-kotlin', 'https://github.com/apollographql/apollo-kotlin', 'android', 'role_path', 'Android Development'),
  ('ChuckerTeam', 'chucker', 'https://github.com/ChuckerTeam/chucker', 'android', 'role_path', 'Android Development'),
  ('detekt', 'detekt', 'https://github.com/detekt/detekt', 'android', 'role_path', 'Android Development'),
  ('JakeWharton', 'timber', 'https://github.com/JakeWharton/timber', 'android', 'role_path', 'Android Development'),
  ('pinterest', 'ktlint', 'https://github.com/pinterest/ktlint', 'android', 'role_path', 'Android Development'),
  ('ReactiveX', 'RxJava', 'https://github.com/ReactiveX/RxJava', 'android', 'role_path', 'Android Development'),
  ('ReactiveX', 'RxKotlin', 'https://github.com/ReactiveX/RxKotlin', 'android', 'role_path', 'Android Development'),
  ('square', 'leakcanary', 'https://github.com/square/leakcanary', 'android', 'role_path', 'Android Development'),
  ('square', 'okhttp', 'https://github.com/square/okhttp', 'android', 'role_path', 'Android Development'),
  ('analogjs', 'analog', 'https://github.com/analogjs/analog', 'angular', 'framework', 'Angular (Web Framework)'),
  ('angular', 'angular', 'https://github.com/angular/angular', 'angular', 'framework', 'Angular (Web Framework)'),
  ('angular', 'vscode-ng-language-service', 'https://github.com/angular/vscode-ng-language-service', 'angular', 'framework', 'Angular (Web Framework)'),
  ('JeanMeche', 'angular-compiler-output', 'https://github.com/JeanMeche/angular-compiler-output', 'angular', 'framework', 'Angular (Web Framework)'),
  ('jsverse', 'transloco', 'https://github.com/jsverse/transloco', 'angular', 'framework', 'Angular (Web Framework)'),
  ('just-jeb', 'angular-builders', 'https://github.com/just-jeb/angular-builders', 'angular', 'framework', 'Angular (Web Framework)'),
  ('ng-packagr', 'ng-packagr', 'https://github.com/ng-packagr/ng-packagr', 'angular', 'framework', 'Angular (Web Framework)'),
  ('ngneat', 'elf', 'https://github.com/ngneat/elf', 'angular', 'framework', 'Angular (Web Framework)'),
  ('ngneat', 'elf-ng-router-store', 'https://github.com/ngneat/elf-ng-router-store', 'angular', 'framework', 'Angular (Web Framework)'),
  ('ngx-translate', 'core', 'https://github.com/ngx-translate/core', 'angular', 'framework', 'Angular (Web Framework)'),
  ('williamjuan027', 'angular-animations-explorer', 'https://github.com/williamjuan027/angular-animations-explorer', 'angular', 'framework', 'Angular (Web Framework)'),
  ('apache', 'kafka', 'https://github.com/apache/kafka', 'api-design', 'practice', 'API Design'),
  ('graphql-kit', 'graphql-apis', 'https://github.com/graphql-kit/graphql-apis', 'api-design', 'practice', 'API Design'),
  ('json-api', 'json-api', 'https://github.com/json-api/json-api', 'api-design', 'practice', 'API Design'),
  ('Redocly', 'redoc', 'https://github.com/Redocly/redoc', 'api-design', 'practice', 'API Design'),
  ('alirezanet', 'Gridify', 'https://github.com/alirezanet/Gridify', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('DotNetAnalyzers', 'StyleCopAnalyzers', 'https://github.com/DotNetAnalyzers/StyleCopAnalyzers', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('LightBDD', 'LightBDD', 'https://github.com/LightBDD/LightBDD', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('MassTransit', 'MassTransit', 'https://github.com/MassTransit/MassTransit', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('microsoft', 'playwright-dotnet', 'https://github.com/microsoft/playwright-dotnet', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('nsubstitute', 'NSubstitute', 'https://github.com/nsubstitute/NSubstitute', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('reqnroll', 'Reqnroll', 'https://github.com/reqnroll/Reqnroll', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('scriban', 'scriban', 'https://github.com/scriban/scriban', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('sebastienros', 'fluid', 'https://github.com/sebastienros/fluid', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('serilog', 'serilog-aspnetcore', 'https://github.com/serilog/serilog-aspnetcore', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('StackExchange', 'Dapper', 'https://github.com/StackExchange/Dapper', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('StyleCop', 'StyleCop', 'https://github.com/StyleCop/StyleCop', 'aspnet-core', 'framework', 'ASP.NET Core'),
  ('0xRadi', 'OWASP-Web-Checklist', 'https://github.com/0xRadi/OWASP-Web-Checklist', 'backend', 'role_path', null),
  ('apache', 'solr', 'https://github.com/apache/solr', 'backend', 'role_path', null),
  ('caddyserver', 'caddy', 'https://github.com/caddyserver/caddy', 'backend', 'role_path', null),
  ('ClickHouse', 'ClickHouse', 'https://github.com/ClickHouse/ClickHouse', 'backend', 'role_path', null),
  ('dgraph-io', 'dgraph', 'https://github.com/dgraph-io/dgraph', 'backend', 'role_path', null),
  ('goldbergyoni', 'javascript-testing-best-practices', 'https://github.com/goldbergyoni/javascript-testing-best-practices', 'backend', 'role_path', null),
  ('kelektiv', 'node.bcrypt.js', 'https://github.com/kelektiv/node.bcrypt.js', 'backend', 'role_path', null),
  ('ladjs', 'supertest', 'https://github.com/ladjs/supertest', 'backend', 'role_path', null),
  ('memcached', 'memcached', 'https://github.com/memcached/memcached', 'backend', 'role_path', null),
  ('modelcontextprotocol', 'modelcontextprotocol', 'https://github.com/modelcontextprotocol/modelcontextprotocol', 'backend', 'role_path', null),
  ('OWASP', 'ASVS', 'https://github.com/OWASP/ASVS', 'backend', 'role_path', null),
  ('resilience4j', 'resilience4j', 'https://github.com/resilience4j/resilience4j', 'backend', 'role_path', null),
  ('scylladb', 'scylladb', 'https://github.com/scylladb/scylladb', 'backend', 'role_path', null),
  ('apache', 'superset', 'https://github.com/apache/superset', 'bi-analyst', 'role_path', null),
  ('metabase', 'metabase', 'https://github.com/metabase/metabase', 'bi-analyst', 'role_path', null),
  ('crytic', 'echidna', 'https://github.com/crytic/echidna', 'blockchain', 'practice', 'Blockchain'),
  ('crytic', 'slither', 'https://github.com/crytic/slither', 'blockchain', 'practice', 'Blockchain'),
  ('Dexaran', 'DAPP-security-standards', 'https://github.com/Dexaran/DAPP-security-standards', 'blockchain', 'practice', 'Blockchain'),
  ('getify', 'You-Dont-Know-JS', 'https://github.com/getify/You-Dont-Know-JS', 'blockchain', 'practice', 'Blockchain'),
  ('hyperledger', 'besu', 'https://github.com/hyperledger/besu', 'blockchain', 'practice', 'Blockchain'),
  ('kadenzipfel', 'smart-contract-attack-vectors', 'https://github.com/kadenzipfel/smart-contract-attack-vectors', 'blockchain', 'practice', 'Blockchain'),
  ('MoralisWeb3', 'Moralis-JS-SDK', 'https://github.com/MoralisWeb3/Moralis-JS-SDK', 'blockchain', 'practice', 'Blockchain'),
  ('libcheck', 'check', 'https://github.com/libcheck/check', 'c', 'language', 'C (Programming Language)'),
  ('ninja-build', 'ninja', 'https://github.com/ninja-build/ninja', 'c', 'language', 'C (Programming Language)'),
  ('throwtheswitch', 'unity', 'https://github.com/throwtheswitch/unity', 'c', 'language', 'C (Programming Language)'),
  ('anthropics', 'claude-code', 'https://github.com/anthropics/claude-code', 'claude-code', 'ai_tooling', null),
  ('darraghh1', 'my-claude-setup', 'https://github.com/darraghh1/my-claude-setup', 'claude-code', 'ai_tooling', null),
  ('cloudflare', 'miniflare', 'https://github.com/cloudflare/miniflare', 'cloudflare', 'data_infrastructure', 'Cloudflare'),
  ('cloudflare', 'workflows-starter', 'https://github.com/cloudflare/workflows-starter', 'cloudflare', 'data_infrastructure', 'Cloudflare'),
  ('honojs', 'examples', 'https://github.com/honojs/examples', 'cloudflare', 'data_infrastructure', 'Cloudflare'),
  ('seemueller-io', 'hyphalbase', 'https://github.com/seemueller-io/hyphalbase', 'cloudflare', 'data_infrastructure', 'Cloudflare'),
  ('google', 'eng-practices', 'https://github.com/google/eng-practices', 'code-review', 'practice', 'Code Review'),
  ('0xRadi', 'OWASP-Web-Checklist', 'https://github.com/0xRadi/OWASP-Web-Checklist', 'computer-science', 'practice', 'Computer Science'),
  ('john-science', 'mazelib', 'https://github.com/john-science/mazelib', 'computer-science', 'practice', 'Computer Science'),
  ('jwasham', 'practice-python', 'https://github.com/jwasham/practice-python', 'computer-science', 'practice', 'Computer Science'),
  ('catchorg', 'Catch2', 'https://github.com/catchorg/Catch2', 'cpp', 'language', 'C++ (Programming Language)'),
  ('conan-io', 'conan', 'https://github.com/conan-io/conan', 'cpp', 'language', 'C++ (Programming Language)'),
  ('Dakkers', 'OpenCL-examples', 'https://github.com/Dakkers/OpenCL-examples', 'cpp', 'language', 'C++ (Programming Language)'),
  ('ericniebler', 'range-v3', 'https://github.com/ericniebler/range-v3', 'cpp', 'language', 'C++ (Programming Language)'),
  ('fmtlib', 'fmt', 'https://github.com/fmtlib/fmt', 'cpp', 'language', 'C++ (Programming Language)'),
  ('gabime', 'spdlog', 'https://github.com/gabime/spdlog', 'cpp', 'language', 'C++ (Programming Language)'),
  ('grpc', 'grpc', 'https://github.com/grpc/grpc', 'cpp', 'language', 'C++ (Programming Language)'),
  ('protocolbuffers', 'protobuf', 'https://github.com/protocolbuffers/protobuf', 'cpp', 'language', 'C++ (Programming Language)'),
  ('pybind', 'pybind11', 'https://github.com/pybind/pybind11', 'cpp', 'language', 'C++ (Programming Language)'),
  ('spack', 'spack', 'https://github.com/spack/spack', 'cpp', 'language', 'C++ (Programming Language)'),
  ('tensorflow', 'tensorflow', 'https://github.com/tensorflow/tensorflow', 'cpp', 'language', 'C++ (Programming Language)'),
  ('postcss', 'postcss', 'https://github.com/postcss/postcss', 'css', 'language', 'Cascading Style Sheets (CSS)'),
  ('labex-labs', 'comptia-linux-plus-training-labs', 'https://github.com/labex-labs/comptia-linux-plus-training-labs', 'cyber-security', 'practice', 'Cyber Security'),
  ('OWASP', 'CheatSheetSeries', 'https://github.com/OWASP/CheatSheetSeries', 'cyber-security', 'practice', 'Cyber Security'),
  ('sergiomarotco', 'Network-segmentation-cheat-sheet', 'https://github.com/sergiomarotco/Network-segmentation-cheat-sheet', 'cyber-security', 'practice', 'Cyber Security'),
  ('tchebb', 'memdump', 'https://github.com/tchebb/memdump', 'cyber-security', 'practice', 'Cyber Security'),
  ('apache', 'spark', 'https://github.com/apache/spark', 'data-analyst', 'role_path', 'Data Analysis'),
  ('aws-samples', 'aws-cdk-examples', 'https://github.com/aws-samples/aws-cdk-examples', 'data-engineer', 'role_path', 'Data Engineering'),
  ('memcached', 'memcached', 'https://github.com/memcached/memcached', 'data-engineer', 'role_path', 'Data Engineering'),
  ('alexpate', 'awesome-design-systems', 'https://github.com/alexpate/awesome-design-systems', 'design-system', 'practice', null),
  ('bitnami-labs', 'sealed-secrets', 'https://github.com/bitnami-labs/sealed-secrets', 'devops', 'role_path', 'DevOps'),
  ('caddyserver', 'caddy', 'https://github.com/caddyserver/caddy', 'devops', 'role_path', 'DevOps'),
  ('chef', 'chef', 'https://github.com/chef/chef', 'devops', 'role_path', 'DevOps'),
  ('envoyproxy', 'envoy', 'https://github.com/envoyproxy/envoy', 'devops', 'role_path', 'DevOps'),
  ('external-secrets', 'external-secrets', 'https://github.com/external-secrets/external-secrets', 'devops', 'role_path', 'DevOps'),
  ('getsops', 'sops', 'https://github.com/getsops/sops', 'devops', 'role_path', 'DevOps'),
  ('Graylog2', 'graylog2-server', 'https://github.com/Graylog2/graylog2-server', 'devops', 'role_path', 'DevOps'),
  ('hashicorp', 'consul-guides', 'https://github.com/hashicorp/consul-guides', 'devops', 'role_path', 'DevOps'),
  ('hashicorp', 'vault', 'https://github.com/hashicorp/vault', 'devops', 'role_path', 'DevOps'),
  ('jaegertracing', 'jaeger', 'https://github.com/jaegertracing/jaeger', 'devops', 'role_path', 'DevOps'),
  ('kubernetes', 'kubernetes', 'https://github.com/kubernetes/kubernetes', 'devops', 'role_path', 'DevOps'),
  ('saltstack', 'salt', 'https://github.com/saltstack/salt', 'devops', 'role_path', 'DevOps'),
  ('getify', 'You-Dont-Know-JS', 'https://github.com/getify/You-Dont-Know-JS', 'devsecops', 'role_path', 'DevSecOps'),
  ('greenbone', 'openvas-scanner', 'https://github.com/greenbone/openvas-scanner', 'devsecops', 'role_path', 'DevSecOps'),
  ('PowerShell', 'PowerShell', 'https://github.com/PowerShell/PowerShell', 'devsecops', 'role_path', 'DevSecOps'),
  ('ruby', 'ruby', 'https://github.com/ruby/ruby', 'devsecops', 'role_path', 'DevSecOps'),
  ('django-commons', 'django-debug-toolbar', 'https://github.com/django-commons/django-debug-toolbar', 'django', 'framework', 'Django (Web Framework)'),
  ('encode', 'django-rest-framework', 'https://github.com/encode/django-rest-framework', 'django', 'framework', 'Django (Web Framework)'),
  ('jazzband', 'django-silk', 'https://github.com/jazzband/django-silk', 'django', 'framework', 'Django (Web Framework)'),
  ('pytest-dev', 'pytest', 'https://github.com/pytest-dev/pytest', 'django', 'framework', 'Django (Web Framework)'),
  ('vitalik', 'django-ninja', 'https://github.com/vitalik/django-ninja', 'django', 'framework', 'Django (Web Framework)'),
  ('docker', 'awesome-compose', 'https://github.com/docker/awesome-compose', 'docker', 'data_infrastructure', 'Docker (Software)'),
  ('engineering-management', 'awesome-engineering-management', 'https://github.com/engineering-management/awesome-engineering-management', 'engineering-manager', 'role_path', null),
  ('nabilnalakath', 'flutter-githubaction', 'https://github.com/nabilnalakath/flutter-githubaction', 'flutter', 'framework', 'Flutter (Software)'),
  ('FrontendMasters', 'front-end-handbook-2019', 'https://github.com/FrontendMasters/front-end-handbook-2019', 'forward-deployed-engineer', 'role_path', null),
  ('sdras', 'awesome-actions', 'https://github.com/sdras/awesome-actions', 'forward-deployed-engineer', 'role_path', null),
  ('0xRadi', 'OWASP-Web-Checklist', 'https://github.com/0xRadi/OWASP-Web-Checklist', 'frontend', 'role_path', 'Frontend Engineering'),
  ('biomejs', 'biome', 'https://github.com/biomejs/biome', 'frontend', 'role_path', 'Frontend Engineering'),
  ('facebook', 'relay', 'https://github.com/facebook/relay', 'frontend', 'role_path', 'Frontend Engineering'),
  ('GoogleChrome', 'lighthouse', 'https://github.com/GoogleChrome/lighthouse', 'frontend', 'role_path', 'Frontend Engineering'),
  ('modelcontextprotocol', 'modelcontextprotocol', 'https://github.com/modelcontextprotocol/modelcontextprotocol', 'frontend', 'role_path', 'Frontend Engineering'),
  ('oven-sh', 'bun', 'https://github.com/oven-sh/bun', 'frontend', 'role_path', 'Frontend Engineering'),
  ('rolldown', 'rolldown', 'https://github.com/rolldown/rolldown', 'frontend', 'role_path', 'Frontend Engineering'),
  ('workshopper', 'how-to-npm', 'https://github.com/workshopper/how-to-npm', 'frontend-beginner', 'role_path', 'Frontend Engineering'),
  ('cheeriojs', 'cheerio', 'https://github.com/cheeriojs/cheerio', 'full-stack', 'role_path', null),
  ('lovell', 'sharp', 'https://github.com/lovell/sharp', 'full-stack', 'role_path', null),
  ('workshopper', 'how-to-npm', 'https://github.com/workshopper/how-to-npm', 'full-stack', 'role_path', null),
  ('godotengine', 'godot', 'https://github.com/godotengine/godot', 'game-developer', 'role_path', null),
  ('rossborchers', 'UnityBoundingVolumeHeirachy', 'https://github.com/rossborchers/UnityBoundingVolumeHeirachy', 'game-developer', 'role_path', null),
  ('adam-p', 'markdown-here', 'https://github.com/adam-p/markdown-here', 'git-github', 'practice', 'Git (Version Control System)'),
  ('apps', 'desktop', 'https://github.com/apps/desktop', 'git-github', 'practice', 'Git (Version Control System)'),
  ('cli', 'cli', 'https://github.com/cli/cli', 'git-github', 'practice', 'Git (Version Control System)'),
  ('git-guides', 'git-commit', 'https://github.com/git-guides/git-commit', 'git-github', 'practice', 'Git (Version Control System)'),
  ('git-guides', 'install-git', 'https://github.com/git-guides/install-git', 'git-github', 'practice', 'Git (Version Control System)'),
  ('gitattributes', 'gitattributes', 'https://github.com/gitattributes/gitattributes', 'git-github', 'practice', 'Git (Version Control System)'),
  ('github', 'gitignore', 'https://github.com/github/gitignore', 'git-github', 'practice', 'Git (Version Control System)'),
  ('mawrkus', 'pull-request-review-guide', 'https://github.com/mawrkus/pull-request-review-guide', 'git-github', 'practice', 'Git (Version Control System)'),
  ('nayafia', 'contributing-template', 'https://github.com/nayafia/contributing-template', 'git-github', 'practice', 'Git (Version Control System)'),
  ('newren', 'git-filter-repo', 'https://github.com/newren/git-filter-repo', 'git-github', 'practice', 'Git (Version Control System)'),
  ('pre-commit', 'pre-commit', 'https://github.com/pre-commit/pre-commit', 'git-github', 'practice', 'Git (Version Control System)'),
  ('user', 'submodule-repo.git', 'https://github.com/user/submodule-repo.git', 'git-github', 'practice', 'Git (Version Control System)'),
  ('beego', 'beego', 'https://github.com/beego/beego', 'golang', 'language', 'Go (Programming Language)'),
  ('centrifugal', 'centrifuge', 'https://github.com/centrifugal/centrifuge', 'golang', 'language', 'Go (Programming Language)'),
  ('charmbracelet', 'bubbletea', 'https://github.com/charmbracelet/bubbletea', 'golang', 'language', 'Go (Programming Language)'),
  ('dominikh', 'go-tools', 'https://github.com/dominikh/go-tools', 'golang', 'language', 'Go (Programming Language)'),
  ('gofiber', 'fiber', 'https://github.com/gofiber/fiber', 'golang', 'language', 'Go (Programming Language)'),
  ('golangci', 'golangci-lint', 'https://github.com/golangci/golangci-lint', 'golang', 'language', 'Go (Programming Language)'),
  ('mgechev', 'revive', 'https://github.com/mgechev/revive', 'golang', 'language', 'Go (Programming Language)'),
  ('olahol', 'melody', 'https://github.com/olahol/melody', 'golang', 'language', 'Go (Programming Language)'),
  ('99designs', 'gqlgen', 'https://github.com/99designs/gqlgen', 'graphql', 'practice', 'GraphQL'),
  ('graphql', 'dataloader', 'https://github.com/graphql/dataloader', 'graphql', 'practice', 'GraphQL'),
  ('graphql', 'graphql-http', 'https://github.com/graphql/graphql-http', 'graphql', 'practice', 'GraphQL'),
  ('graphql', 'graphql-js', 'https://github.com/graphql/graphql-js', 'graphql', 'practice', 'GraphQL'),
  ('graphql-go', 'graphql', 'https://github.com/graphql-go/graphql', 'graphql', 'practice', 'GraphQL'),
  ('graphql-java', 'graphql-java', 'https://github.com/graphql-java/graphql-java', 'graphql', 'practice', 'GraphQL'),
  ('graphql-python', 'graphene', 'https://github.com/graphql-python/graphene', 'graphql', 'practice', 'GraphQL'),
  ('mercurius-js', 'mercurius', 'https://github.com/mercurius-js/mercurius', 'graphql', 'practice', 'GraphQL'),
  ('getify', 'You-Dont-Know-JS', 'https://github.com/getify/You-Dont-Know-JS', 'html', 'language', 'HyperText Markup Language (HTML)'),
  ('airbnb', 'lottie-ios', 'https://github.com/airbnb/lottie-ios', 'ios', 'role_path', 'IOS Development'),
  ('Alamofire', 'Alamofire', 'https://github.com/Alamofire/Alamofire', 'ios', 'role_path', 'IOS Development'),
  ('Carthage', 'Carthage', 'https://github.com/Carthage/Carthage', 'ios', 'role_path', 'IOS Development'),
  ('fastlane', 'fastlane', 'https://github.com/fastlane/fastlane', 'ios', 'role_path', 'IOS Development'),
  ('nicklockwood', 'SwiftFormat', 'https://github.com/nicklockwood/SwiftFormat', 'ios', 'role_path', 'IOS Development'),
  ('pointfreeco', 'swift-composable-architecture', 'https://github.com/pointfreeco/swift-composable-architecture', 'ios', 'role_path', 'IOS Development'),
  ('pointfreeco', 'swiftui-navigation', 'https://github.com/pointfreeco/swiftui-navigation', 'ios', 'role_path', 'IOS Development'),
  ('ReactiveX', 'RxSwift', 'https://github.com/ReactiveX/RxSwift', 'ios', 'role_path', 'IOS Development'),
  ('realm', 'SwiftLint', 'https://github.com/realm/SwiftLint', 'ios', 'role_path', 'IOS Development'),
  ('russell-archer', 'ModalStylesDemo', 'https://github.com/russell-archer/ModalStylesDemo', 'ios', 'role_path', 'IOS Development'),
  ('sleekbyte', 'tailor', 'https://github.com/sleekbyte/tailor', 'ios', 'role_path', 'IOS Development'),
  ('stephencelis', 'SQLite.swift', 'https://github.com/stephencelis/SQLite.swift', 'ios', 'role_path', 'IOS Development'),
  ('yokurin', 'RxSwift-MVVM-iOS', 'https://github.com/yokurin/RxSwift-MVVM-iOS', 'ios', 'role_path', 'IOS Development'),
  ('rest-assured', 'rest-assured', 'https://github.com/rest-assured/rest-assured', 'java', 'language', 'Java (Programming Language)'),
  ('getify', 'You-Dont-Know-JS', 'https://github.com/getify/You-Dont-Know-JS', 'javascript', 'language', 'JavaScript (Programming Language)'),
  ('JetBrains', 'compose-multiplatform', 'https://github.com/JetBrains/compose-multiplatform', 'kotlin', 'language', 'Kotlin'),
  ('JetBrains', 'intellij-community', 'https://github.com/JetBrains/intellij-community', 'kotlin', 'language', 'Kotlin'),
  ('JetBrains', 'koog', 'https://github.com/JetBrains/koog', 'kotlin', 'language', 'Kotlin'),
  ('Kotlin', 'dataframe', 'https://github.com/Kotlin/dataframe', 'kotlin', 'language', 'Kotlin'),
  ('Kotlin', 'kandy', 'https://github.com/Kotlin/kandy', 'kotlin', 'language', 'Kotlin'),
  ('Kotlin', 'Kotlin-AI-Examples', 'https://github.com/Kotlin/Kotlin-AI-Examples', 'kotlin', 'language', 'Kotlin'),
  ('Kotlin', 'kotlinx-datetime', 'https://github.com/Kotlin/kotlinx-datetime', 'kotlin', 'language', 'Kotlin'),
  ('Kotlin', 'kotlinx-io', 'https://github.com/Kotlin/kotlinx-io', 'kotlin', 'language', 'Kotlin'),
  ('Kotlin', 'kotlinx.coroutines', 'https://github.com/Kotlin/kotlinx.coroutines', 'kotlin', 'language', 'Kotlin'),
  ('Kotlin', 'kotlinx.serialization', 'https://github.com/Kotlin/kotlinx.serialization', 'kotlin', 'language', 'Kotlin'),
  ('ktorio', 'ktor', 'https://github.com/ktorio/ktor', 'kotlin', 'language', 'Kotlin'),
  ('k8sgpt-ai', 'k8sgpt', 'https://github.com/k8sgpt-ai/k8sgpt', 'kubernetes', 'data_infrastructure', 'Kubernetes'),
  ('robusta-dev', 'holmesgpt', 'https://github.com/robusta-dev/holmesgpt', 'kubernetes', 'data_infrastructure', 'Kubernetes'),
  ('barryvdh', 'laravel-debugbar', 'https://github.com/barryvdh/laravel-debugbar', 'laravel', 'framework', 'Laravel'),
  ('inertiajs', 'inertia-laravel', 'https://github.com/inertiajs/inertia-laravel', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'breeze', 'https://github.com/laravel/breeze', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'jetstream', 'https://github.com/laravel/jetstream', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'octane', 'https://github.com/laravel/octane', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'passport', 'https://github.com/laravel/passport', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'pint', 'https://github.com/laravel/pint', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'sail', 'https://github.com/laravel/sail', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'sanctum', 'https://github.com/laravel/sanctum', 'laravel', 'framework', 'Laravel'),
  ('laravel', 'telescope', 'https://github.com/laravel/telescope', 'laravel', 'framework', 'Laravel'),
  ('livewire', 'livewire', 'https://github.com/livewire/livewire', 'laravel', 'framework', 'Laravel'),
  ('sebastianbergmann', 'phpunit', 'https://github.com/sebastianbergmann/phpunit', 'laravel', 'framework', 'Laravel'),
  ('BurntSushi', 'ripgrep', 'https://github.com/BurntSushi/ripgrep', 'linux', 'data_infrastructure', 'Linux'),
  ('tldr-pages', 'tldr', 'https://github.com/tldr-pages/tldr', 'linux', 'data_infrastructure', 'Linux'),
  ('alexjungaalto', 'MachineLearningTheBasics', 'https://github.com/alexjungaalto/MachineLearningTheBasics', 'machine-learning', 'ai_tooling', 'Machine Learning'),
  ('keras-team', 'keras', 'https://github.com/keras-team/keras', 'machine-learning', 'ai_tooling', 'Machine Learning'),
  ('numpy', 'numpy', 'https://github.com/numpy/numpy', 'machine-learning', 'ai_tooling', 'Machine Learning'),
  ('scikit-learn', 'scikit-learn', 'https://github.com/scikit-learn/scikit-learn', 'machine-learning', 'ai_tooling', 'Machine Learning'),
  ('apache', 'airflow', 'https://github.com/apache/airflow', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('Idnan', 'bash-guide', 'https://github.com/Idnan/bash-guide', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('kubeflow', 'kubeflow', 'https://github.com/kubeflow/kubeflow', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('marcotcr', 'lime', 'https://github.com/marcotcr/lime', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('mlflow', 'mlflow', 'https://github.com/mlflow/mlflow', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('pytorch', 'executorch', 'https://github.com/pytorch/executorch', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('scikit-learn', 'scikit-learn', 'https://github.com/scikit-learn/scikit-learn', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('shap', 'shap', 'https://github.com/shap/shap', 'mlops', 'ai_tooling', 'MLOps (Machine Learning Operations)'),
  ('GNS3', 'gns3-gui', 'https://github.com/GNS3/gns3-gui', 'network-engineer', 'role_path', null),
  ('nmap', 'nmap', 'https://github.com/nmap/nmap', 'network-engineer', 'role_path', null),
  ('wireshark', 'wireshark', 'https://github.com/wireshark/wireshark', 'network-engineer', 'role_path', null),
  ('prettier', 'eslint-config-prettier', 'https://github.com/prettier/eslint-config-prettier', 'nextjs', 'framework', 'Next.js (Javascript Library)'),
  ('sass', 'sass', 'https://github.com/sass/sass', 'nextjs', 'framework', 'Next.js (Javascript Library)'),
  ('vercel', 'next.js', 'https://github.com/vercel/next.js', 'nextjs', 'framework', 'Next.js (Javascript Library)'),
  ('chalk', 'chalk', 'https://github.com/chalk/chalk', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('drizzle-team', 'drizzle-orm', 'https://github.com/drizzle-team/drizzle-orm', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('motdotla', 'dotenv', 'https://github.com/motdotla/dotenv', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('patorjk', 'figlet.js', 'https://github.com/patorjk/figlet.js', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('SBoudrias', 'Inquirer.js', 'https://github.com/SBoudrias/Inquirer.js', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('sindresorhus', 'globby', 'https://github.com/sindresorhus/globby', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('sindresorhus', 'ky', 'https://github.com/sindresorhus/ky', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('winstonjs', 'winston', 'https://github.com/winstonjs/winston', 'nodejs', 'framework', 'Node.js (Javascript Library)'),
  ('hesamsheikh', 'awesome-openclaw-usecases', 'https://github.com/hesamsheikh/awesome-openclaw-usecases', 'openclaw', 'ai_tooling', null),
  ('mergisi', 'awesome-openclaw-agents', 'https://github.com/mergisi/awesome-openclaw-agents', 'openclaw', 'ai_tooling', null),
  ('curl', 'curl', 'https://github.com/curl/curl', 'php', 'language', 'PHP (Scripting Language)'),
  ('phan', 'phan', 'https://github.com/phan/phan', 'php', 'language', 'PHP (Scripting Language)'),
  ('PHPCSStandards', 'PHP_CodeSniffer', 'https://github.com/PHPCSStandards/PHP_CodeSniffer', 'php', 'language', 'PHP (Scripting Language)'),
  ('acassen', 'keepalived', 'https://github.com/acassen/keepalived', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('ansible', 'ansible', 'https://github.com/ansible/ansible', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('chef', 'chef', 'https://github.com/chef/chef', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('dalibo', 'PAF', 'https://github.com/dalibo/PAF', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('dalibo', 'pev2', 'https://github.com/dalibo/pev2', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('dalibo', 'postgresql_anonymizer', 'https://github.com/dalibo/postgresql_anonymizer', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('dalibo', 'temboard', 'https://github.com/dalibo/temboard', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('darold', 'pgbadger', 'https://github.com/darold/pgbadger', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('darold', 'pgcluu', 'https://github.com/darold/pgcluu', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('EnterpriseDB', 'barman', 'https://github.com/EnterpriseDB/barman', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('hashicorp', 'consul', 'https://github.com/hashicorp/consul', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('helm', 'helm', 'https://github.com/helm/helm', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('lesovsky', 'pgcenter', 'https://github.com/lesovsky/pgcenter', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('OPMDG', 'check_pgactivity', 'https://github.com/OPMDG/check_pgactivity', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('patroni', 'patroni', 'https://github.com/patroni/patroni', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('pgbackrest', 'pgbackrest', 'https://github.com/pgbackrest/pgbackrest', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('pgbouncer', 'pgbouncer', 'https://github.com/pgbouncer/pgbouncer', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('postgrespro', 'pg_probackup', 'https://github.com/postgrespro/pg_probackup', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('saltstack', 'salt', 'https://github.com/saltstack/salt', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('sorintlab', 'stolon', 'https://github.com/sorintlab/stolon', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('sysstat', 'sysstat', 'https://github.com/sysstat/sysstat', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('wal-g', 'wal-g', 'https://github.com/wal-g/wal-g', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('yandex', 'odyssey', 'https://github.com/yandex/odyssey', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('zabbix', 'zabbix', 'https://github.com/zabbix/zabbix', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('zalando', 'patroni', 'https://github.com/zalando/patroni', 'postgresql-dba', 'data_infrastructure', 'PostgreSQL'),
  ('jxnl', 'instructor', 'https://github.com/jxnl/instructor', 'prompt-engineering', 'practice', 'Prompt Engineering'),
  ('meta-llama', 'llama-models', 'https://github.com/meta-llama/llama-models', 'prompt-engineering', 'practice', 'Prompt Engineering'),
  ('openai', 'openai-cookbook', 'https://github.com/openai/openai-cookbook', 'prompt-engineering', 'practice', 'Prompt Engineering'),
  ('astral-sh', 'uv', 'https://github.com/astral-sh/uv', 'python', 'language', 'Python (Programming Language)'),
  ('gevent', 'gevent', 'https://github.com/gevent/gevent', 'python', 'language', 'Python (Programming Language)'),
  ('google', 'yapf', 'https://github.com/google/yapf', 'python', 'language', 'Python (Programming Language)'),
  ('pdm-project', 'pdm', 'https://github.com/pdm-project/pdm', 'python', 'language', 'Python (Programming Language)'),
  ('pyenv', 'pyenv', 'https://github.com/pyenv/pyenv', 'python', 'language', 'Python (Programming Language)'),
  ('pypa', 'pipx', 'https://github.com/pypa/pipx', 'python', 'language', 'Python (Programming Language)'),
  ('python', 'mypy', 'https://github.com/python/mypy', 'python', 'language', 'Python (Programming Language)'),
  ('sanic-org', 'sanic', 'https://github.com/sanic-org/sanic', 'python', 'language', 'Python (Programming Language)'),
  ('pypa', 'pip', 'https://github.com/pypa/pip', 'python-data-analysis', 'language', 'Python For Data Analysis'),
  ('android', 'testing-samples', 'https://github.com/android/testing-samples', 'qa', 'role_path', 'Quality Assurance'),
  ('appium', 'appium', 'https://github.com/appium/appium', 'qa', 'role_path', 'Quality Assurance'),
  ('tsenart', 'vegeta', 'https://github.com/tsenart/vegeta', 'qa', 'role_path', 'Quality Assurance'),
  ('plotly', 'plotly.R', 'https://github.com/plotly/plotly.R', 'r', 'language', 'R (Programming Language)'),
  ('quanteda', 'quanteda', 'https://github.com/quanteda/quanteda', 'r', 'language', 'R (Programming Language)'),
  ('r-lib', 'pak', 'https://github.com/r-lib/pak', 'r', 'language', 'R (Programming Language)'),
  ('rstudio', 'shiny', 'https://github.com/rstudio/shiny', 'r', 'language', 'R (Programming Language)'),
  ('plotly', 'plotly.R', 'https://github.com/plotly/plotly.R', 'r-programming', 'language', 'R (Programming Language)'),
  ('quanteda', 'quanteda', 'https://github.com/quanteda/quanteda', 'r-programming', 'language', 'R (Programming Language)'),
  ('r-lib', 'pak', 'https://github.com/r-lib/pak', 'r-programming', 'language', 'R (Programming Language)'),
  ('rstudio', 'shiny', 'https://github.com/rstudio/shiny', 'r-programming', 'language', 'R (Programming Language)'),
  ('css-modules', 'css-modules', 'https://github.com/css-modules/css-modules', 'react', 'framework', 'React.js (Javascript Library)'),
  ('formik', 'formik', 'https://github.com/formik/formik', 'react', 'framework', 'React.js (Javascript Library)'),
  ('open-circle', 'formisch', 'https://github.com/open-circle/formisch', 'react', 'framework', 'React.js (Javascript Library)'),
  ('open-circle', 'valibot', 'https://github.com/open-circle/valibot', 'react', 'framework', 'React.js (Javascript Library)'),
  ('pmndrs', 'zustand', 'https://github.com/pmndrs/zustand', 'react', 'framework', 'React.js (Javascript Library)'),
  ('react-hook-form', 'react-hook-form', 'https://github.com/react-hook-form/react-hook-form', 'react', 'framework', 'React.js (Javascript Library)'),
  ('remix-run', 'react-router', 'https://github.com/remix-run/react-router', 'react', 'framework', 'React.js (Javascript Library)'),
  ('TanStack', 'query', 'https://github.com/TanStack/query', 'react', 'framework', 'React.js (Javascript Library)'),
  ('callstack', 'react-native-testing-library', 'https://github.com/callstack/react-native-testing-library', 'react-native', 'framework', 'React Native'),
  ('react-native-async-storage', 'async-storage', 'https://github.com/react-native-async-storage/async-storage', 'react-native', 'framework', 'React Native'),
  ('react-native-community', 'cli', 'https://github.com/react-native-community/cli', 'react-native', 'framework', 'React Native'),
  ('react-native-netinfo', 'react-native-netinfo', 'https://github.com/react-native-netinfo/react-native-netinfo', 'react-native', 'framework', 'React Native'),
  ('realm', 'realm-js', 'https://github.com/realm/realm-js', 'react-native', 'framework', 'React Native'),
  ('zoontek', 'react-native-permissions', 'https://github.com/zoontek/react-native-permissions', 'react-native', 'framework', 'React Native'),
  ('joeferner', 'redis-commander', 'https://github.com/joeferner/redis-commander', 'redis', 'data_infrastructure', 'Redis'),
  ('RedisBloom', 'RedisBloom', 'https://github.com/RedisBloom/RedisBloom', 'redis', 'data_infrastructure', 'Redis'),
  ('RedisInsight', 'RedisInsight', 'https://github.com/RedisInsight/RedisInsight', 'redis', 'data_infrastructure', 'Redis'),
  ('RedisJSON', 'RedisJSON', 'https://github.com/RedisJSON/RedisJSON', 'redis', 'data_infrastructure', 'Redis'),
  ('deivid-rodriguez', 'byebug', 'https://github.com/deivid-rodriguez/byebug', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('lsegal', 'yard', 'https://github.com/lsegal/yard', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('maniramakumar', 'the-best-ruby-books', 'https://github.com/maniramakumar/the-best-ruby-books', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('minitest', 'minitest', 'https://github.com/minitest/minitest', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('postmodern', 'ruby-install', 'https://github.com/postmodern/ruby-install', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('rack', 'rack', 'https://github.com/rack/rack', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('rails', 'rails', 'https://github.com/rails/rails', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('rbenv', 'rbenv', 'https://github.com/rbenv/rbenv', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('rbenv', 'ruby-build', 'https://github.com/rbenv/ruby-build', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('rubocop', 'rubocop', 'https://github.com/rubocop/rubocop', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('ruby', 'debug', 'https://github.com/ruby/debug', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('ruby', 'rdoc', 'https://github.com/ruby/rdoc', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('ruby', 'rubygems', 'https://github.com/ruby/rubygems', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('ruby-concurrency', 'concurrent-ruby', 'https://github.com/ruby-concurrency/concurrent-ruby', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('rvm', 'rvm', 'https://github.com/rvm/rvm', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('sinatra', 'sinatra', 'https://github.com/sinatra/sinatra', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('standardrb', 'standard', 'https://github.com/standardrb/standard', 'ruby', 'language', 'Ruby (Programming Language)'),
  ('basecamp', 'kamal', 'https://github.com/basecamp/kamal', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('CanCanCommunity', 'cancancan', 'https://github.com/CanCanCommunity/cancancan', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('ddnexus', 'pagy', 'https://github.com/ddnexus/pagy', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('heartcombo', 'devise', 'https://github.com/heartcombo/devise', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('kaminari', 'kaminari', 'https://github.com/kaminari/kaminari', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('minitest', 'minitest', 'https://github.com/minitest/minitest', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('pry', 'pry', 'https://github.com/pry/pry', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('rspec', 'rspec-rails', 'https://github.com/rspec/rspec-rails', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('teamcapybara', 'capybara', 'https://github.com/teamcapybara/capybara', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('thoughtbot', 'factory_bot_rails', 'https://github.com/thoughtbot/factory_bot_rails', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('varvet', 'pundit', 'https://github.com/varvet/pundit', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('ViewComponent', 'view_component', 'https://github.com/ViewComponent/view_component', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('yippee-fun', 'phlex-rails', 'https://github.com/yippee-fun/phlex-rails', 'ruby-on-rails', 'framework', 'Ruby On Rails'),
  ('baldwin-sudo', 'rusty-utils', 'https://github.com/baldwin-sudo/rusty-utils', 'rust', 'language', 'Rust (Programming Language)'),
  ('bevyengine', 'bevy', 'https://github.com/bevyengine/bevy', 'rust', 'language', 'Rust (Programming Language)'),
  ('briansmith', 'ring', 'https://github.com/briansmith/ring', 'rust', 'language', 'Rust (Programming Language)'),
  ('diesel-rs', 'diesel', 'https://github.com/diesel-rs/diesel', 'rust', 'language', 'Rust (Programming Language)'),
  ('FyroxEngine', 'Fyrox', 'https://github.com/FyroxEngine/Fyrox', 'rust', 'language', 'Rust (Programming Language)'),
  ('gfx-rs', 'wgpu', 'https://github.com/gfx-rs/wgpu', 'rust', 'language', 'Rust (Programming Language)'),
  ('golemparts', 'rppal', 'https://github.com/golemparts/rppal', 'rust', 'language', 'Rust (Programming Language)'),
  ('gtk-rs', 'gtk4-rs', 'https://github.com/gtk-rs/gtk4-rs', 'rust', 'language', 'Rust (Programming Language)'),
  ('launchbadge', 'sqlx', 'https://github.com/launchbadge/sqlx', 'rust', 'language', 'Rust (Programming Language)'),
  ('leptos-rs', 'leptos', 'https://github.com/leptos-rs/leptos', 'rust', 'language', 'Rust (Programming Language)'),
  ('nrf-rs', 'nrf-hal', 'https://github.com/nrf-rs/nrf-hal', 'rust', 'language', 'Rust (Programming Language)'),
  ('quinn-rs', 'quinn', 'https://github.com/quinn-rs/quinn', 'rust', 'language', 'Rust (Programming Language)'),
  ('rusqlite', 'rusqlite', 'https://github.com/rusqlite/rusqlite', 'rust', 'language', 'Rust (Programming Language)'),
  ('rust-embedded', 'embedded-hal', 'https://github.com/rust-embedded/embedded-hal', 'rust', 'language', 'Rust (Programming Language)'),
  ('rustwasm', 'wasm-bindgen', 'https://github.com/rustwasm/wasm-bindgen', 'rust', 'language', 'Rust (Programming Language)'),
  ('rustwasm', 'wasm-pack', 'https://github.com/rustwasm/wasm-pack', 'rust', 'language', 'Rust (Programming Language)'),
  ('serde-rs', 'serde', 'https://github.com/serde-rs/serde', 'rust', 'language', 'Rust (Programming Language)'),
  ('smol-rs', 'smol', 'https://github.com/smol-rs/smol', 'rust', 'language', 'Rust (Programming Language)'),
  ('toml-rs', 'toml-rs', 'https://github.com/toml-rs/toml-rs', 'rust', 'language', 'Rust (Programming Language)'),
  ('wasmerio', 'wasmer', 'https://github.com/wasmerio/wasmer', 'rust', 'language', 'Rust (Programming Language)'),
  ('zed-industries', 'zed', 'https://github.com/zed-industries/zed', 'rust', 'language', 'Rust (Programming Language)'),
  ('armanbilge', 'calico', 'https://github.com/armanbilge/calico', 'scala', 'language', 'Scala (Programming Language)'),
  ('com-lihaoyi', 'utest', 'https://github.com/com-lihaoyi/utest', 'scala', 'language', 'Scala (Programming Language)'),
  ('http4s', 'http4s', 'https://github.com/http4s/http4s', 'scala', 'language', 'Scala (Programming Language)'),
  ('makingthematrix', 'scalaonandroid', 'https://github.com/makingthematrix/scalaonandroid', 'scala', 'language', 'Scala (Programming Language)'),
  ('onsqcorp', 'scala-android-plugin', 'https://github.com/onsqcorp/scala-android-plugin', 'scala', 'language', 'Scala (Programming Language)'),
  ('rathboma', 'scala-libgdx-examples', 'https://github.com/rathboma/scala-libgdx-examples', 'scala', 'language', 'Scala (Programming Language)'),
  ('scala-native', 'scala-native', 'https://github.com/scala-native/scala-native', 'scala', 'language', 'Scala (Programming Language)'),
  ('scalameta', 'sbt-native-image', 'https://github.com/scalameta/sbt-native-image', 'scala', 'language', 'Scala (Programming Language)'),
  ('scalatra', 'scalatra', 'https://github.com/scalatra/scalatra', 'scala', 'language', 'Scala (Programming Language)'),
  ('typelevel', 'cats', 'https://github.com/typelevel/cats', 'scala', 'language', 'Scala (Programming Language)'),
  ('typelevel', 'cats-effect', 'https://github.com/typelevel/cats-effect', 'scala', 'language', 'Scala (Programming Language)'),
  ('VirtusLab', 'scala-cli', 'https://github.com/VirtusLab/scala-cli', 'scala', 'language', 'Scala (Programming Language)'),
  ('zio', 'zio', 'https://github.com/zio/zio', 'scala', 'language', 'Scala (Programming Language)'),
  ('dckc', 'awesome-ocap', 'https://github.com/dckc/awesome-ocap', 'server-side-game-developer', 'role_path', null),
  ('docker', 'getting-started', 'https://github.com/docker/getting-started', 'server-side-game-developer', 'role_path', null),
  ('microsoft', 'Windows-classic-samples', 'https://github.com/microsoft/Windows-classic-samples', 'server-side-game-developer', 'role_path', null),
  ('pietrobassi', 'deterministic-lockstep-demo', 'https://github.com/pietrobassi/deterministic-lockstep-demo', 'server-side-game-developer', 'role_path', null),
  ('toml-lang', 'toml', 'https://github.com/toml-lang/toml', 'server-side-game-developer', 'role_path', null),
  ('uxlfoundation', 'oneTBB', 'https://github.com/uxlfoundation/oneTBB', 'server-side-game-developer', 'role_path', null),
  ('curl', 'curl', 'https://github.com/curl/curl', 'shell-bash', 'language', 'Bash (Scripting Language)'),
  ('fish-shell', 'fish-shell', 'https://github.com/fish-shell/fish-shell', 'shell-bash', 'language', 'Bash (Scripting Language)'),
  ('koalaman', 'shellcheck', 'https://github.com/koalaman/shellcheck', 'shell-bash', 'language', 'Bash (Scripting Language)'),
  ('PowerShell', 'PowerShell', 'https://github.com/PowerShell/PowerShell', 'shell-bash', 'language', 'Bash (Scripting Language)'),
  ('rogalmic', 'vscode-bash-debug', 'https://github.com/rogalmic/vscode-bash-debug', 'shell-bash', 'language', 'Bash (Scripting Language)'),
  ('0xRadi', 'OWASP-Web-Checklist', 'https://github.com/0xRadi/OWASP-Web-Checklist', 'software-architect', 'role_path', 'Software Architecture'),
  ('ddd-crew', 'ddd-starter-modelling-process', 'https://github.com/ddd-crew/ddd-starter-modelling-process', 'software-architect', 'role_path', 'Software Architecture'),
  ('Alamofire', 'Alamofire', 'https://github.com/Alamofire/Alamofire', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('apple', 'swift-log', 'https://github.com/apple/swift-log', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('apple', 'swift-nio', 'https://github.com/apple/swift-nio', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('CocoaLumberjack', 'CocoaLumberjack', 'https://github.com/CocoaLumberjack/CocoaLumberjack', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('groue', 'GRDB.swift', 'https://github.com/groue/GRDB.swift', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('hummingbird-project', 'hummingbird', 'https://github.com/hummingbird-project/hummingbird', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('Moya', 'Moya', 'https://github.com/Moya/Moya', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('neovim', 'neovim', 'https://github.com/neovim/neovim', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('orlandos-nl', 'MongoKitten', 'https://github.com/orlandos-nl/MongoKitten', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('realm', 'realm-swift', 'https://github.com/realm/realm-swift', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('swiftlang', 'swift-package-manager', 'https://github.com/swiftlang/swift-package-manager', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('swiftlang', 'swift-testing', 'https://github.com/swiftlang/swift-testing', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('vapor', 'vapor', 'https://github.com/vapor/vapor', 'swift-ui', 'framework', 'Swift (Programming Language)'),
  ('donnemartin', 'system-design-primer', 'https://github.com/donnemartin/system-design-primer', 'system-design', 'practice', null),
  ('henryr', 'cap-faq', 'https://github.com/henryr/cap-faq', 'system-design', 'practice', null),
  ('aquasecurity', 'trivy', 'https://github.com/aquasecurity/trivy', 'terraform', 'data_infrastructure', 'Terraform'),
  ('bridgecrewio', 'checkov', 'https://github.com/bridgecrewio/checkov', 'terraform', 'data_infrastructure', 'Terraform'),
  ('Checkmarx', 'kics', 'https://github.com/Checkmarx/kics', 'terraform', 'data_infrastructure', 'Terraform'),
  ('gruntwork-io', 'terragrunt', 'https://github.com/gruntwork-io/terragrunt', 'terraform', 'data_infrastructure', 'Terraform'),
  ('hashicorp', 'hcl', 'https://github.com/hashicorp/hcl', 'terraform', 'data_infrastructure', 'Terraform'),
  ('hashicorp', 'hcp-auth-action', 'https://github.com/hashicorp/hcp-auth-action', 'terraform', 'data_infrastructure', 'Terraform'),
  ('hashicorp', 'setup-terraform', 'https://github.com/hashicorp/setup-terraform', 'terraform', 'data_infrastructure', 'Terraform'),
  ('hashicorp', 'terraform-sentinel-policies', 'https://github.com/hashicorp/terraform-sentinel-policies', 'terraform', 'data_infrastructure', 'Terraform'),
  ('infracost', 'infracost', 'https://github.com/infracost/infracost', 'terraform', 'data_infrastructure', 'Terraform'),
  ('tenable', 'terrascan', 'https://github.com/tenable/terrascan', 'terraform', 'data_infrastructure', 'Terraform'),
  ('terraform-linters', 'tflint', 'https://github.com/terraform-linters/tflint', 'terraform', 'data_infrastructure', 'Terraform'),
  ('tfutils', 'tfenv', 'https://github.com/tfutils/tfenv', 'terraform', 'data_infrastructure', 'Terraform'),
  ('dsherret', 'ts-morph', 'https://github.com/dsherret/ts-morph', 'typescript', 'language', 'TypeScript'),
  ('jeffijoe', 'typesync', 'https://github.com/jeffijoe/typesync', 'typescript', 'language', 'TypeScript'),
  ('kulshekhar', 'ts-jest', 'https://github.com/kulshekhar/ts-jest', 'typescript', 'language', 'TypeScript'),
  ('TypeStrong', 'ts-node', 'https://github.com/TypeStrong/ts-node', 'typescript', 'language', 'TypeScript'),
  ('kurdin', 'ai-coding-best-practices-for-modern-development', 'https://github.com/kurdin/ai-coding-best-practices-for-modern-development', 'vibe-coding', 'ai_tooling', null),
  ('logaretm', 'vee-validate', 'https://github.com/logaretm/vee-validate', 'vue', 'framework', 'Vue.js (Javascript Library)'),
  ('vuejs', 'create-vue', 'https://github.com/vuejs/create-vue', 'vue', 'framework', 'Vue.js (Javascript Library)'),
  ('vuelidate', 'vuelidate', 'https://github.com/vuelidate/vuelidate', 'vue', 'framework', 'Vue.js (Javascript Library)'),
  ('roots', 'bedrock', 'https://github.com/roots/bedrock', 'wordpress', 'framework', 'WordPress'),
  ('roots', 'sage', 'https://github.com/roots/sage', 'wordpress', 'framework', 'WordPress'),
  ('Varying-Vagrant-Vagrants', 'VVV', 'https://github.com/Varying-Vagrant-Vagrants/VVV', 'wordpress', 'framework', 'WordPress')
on conflict (owner, name, roadmap_slug) do update
    set html_url = excluded.html_url,
        use_case = excluded.use_case,
        taxonomy_key = excluded.taxonomy_key;

notify pgrst, 'reload schema';

commit;
