-- An outbound click is an attempt, not proof that an application was submitted.
-- Keep each click idempotent by client event ID and enrich it with server-owned
-- listing trust at the instant the user leaves Myro.

CREATE TABLE IF NOT EXISTS public.job_apply_intents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    job_id text NOT NULL,
    client_event_id uuid NOT NULL,
    surface text NOT NULL,
    destination_type text NOT NULL,
    verified_live_at timestamptz,
    confidence_at_click text,
    enrichment_status text,
    event_day date NOT NULL DEFAULT CURRENT_DATE,
    clicked_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.job_apply_intents
    ADD COLUMN IF NOT EXISTS client_event_id uuid;

UPDATE public.job_apply_intents
SET client_event_id = gen_random_uuid()
WHERE client_event_id IS NULL;

ALTER TABLE public.job_apply_intents
    ALTER COLUMN client_event_id SET NOT NULL,
    DROP CONSTRAINT IF EXISTS job_apply_intents_user_id_job_id_event_day_surface_key,
    DROP CONSTRAINT IF EXISTS job_apply_intents_surface_check,
    DROP CONSTRAINT IF EXISTS job_apply_intents_destination_type_check,
    DROP CONSTRAINT IF EXISTS job_apply_intents_confidence_at_click_check;

ALTER TABLE public.job_apply_intents
    ADD CONSTRAINT job_apply_intents_surface_check CHECK (surface IN (
        'dashboard', 'market', 'collections', 'cv_playground', 'cv_export',
        'mobile_jobs', 'mobile_collections', 'agent_pick', 'other'
    )),
    ADD CONSTRAINT job_apply_intents_destination_type_check CHECK (
        destination_type IN ('direct_role', 'career_search')
    ),
    ADD CONSTRAINT job_apply_intents_confidence_at_click_check CHECK (
        confidence_at_click IS NULL OR confidence_at_click IN (
            'active', 'uncertain', 'likely_closed', 'closed'
        )
    );

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.job_apply_intents'::regclass
          AND conname = 'job_apply_intents_user_id_client_event_id_key'
    ) THEN
        ALTER TABLE public.job_apply_intents
            ADD CONSTRAINT job_apply_intents_user_id_client_event_id_key
            UNIQUE (user_id, client_event_id);
    END IF;
END;
$$;

ALTER TABLE public.job_apply_intents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS job_apply_intents_own_select ON public.job_apply_intents;
DROP POLICY IF EXISTS job_apply_intents_own_insert ON public.job_apply_intents;

CREATE POLICY job_apply_intents_own_select
    ON public.job_apply_intents
    FOR SELECT
    TO authenticated
    USING (
        (SELECT auth.uid()) = user_id
        AND (((SELECT auth.jwt()) ->> 'is_anonymous')::boolean) IS FALSE
    );

CREATE POLICY job_apply_intents_own_insert
    ON public.job_apply_intents
    FOR INSERT
    TO authenticated
    WITH CHECK (
        (SELECT auth.uid()) = user_id
        AND (((SELECT auth.jwt()) ->> 'is_anonymous')::boolean) IS FALSE
    );

REVOKE ALL ON TABLE public.job_apply_intents FROM PUBLIC, anon;
GRANT SELECT, INSERT ON TABLE public.job_apply_intents TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.job_apply_intents_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.record_job_apply_intent(
    p_job_id text,
    p_client_event_id uuid,
    p_surface text,
    p_destination_type text
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_user_id uuid := (SELECT auth.uid());
BEGIN
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF (((SELECT auth.jwt()) ->> 'is_anonymous')::boolean) IS DISTINCT FROM FALSE THEN
        RAISE EXCEPTION 'Permanent account required' USING ERRCODE = '42501';
    END IF;

    INSERT INTO public.job_apply_intents (
        user_id,
        job_id,
        client_event_id,
        surface,
        destination_type,
        verified_live_at,
        confidence_at_click,
        enrichment_status,
        clicked_at
    )
    VALUES (
        v_user_id,
        p_job_id,
        p_client_event_id,
        p_surface,
        p_destination_type,
        (
            SELECT job.last_verified_live_at
            FROM public.jobs AS job
            WHERE job.job_id = p_job_id
            LIMIT 1
        ),
        (
            SELECT job.listing_confidence
            FROM public.jobs AS job
            WHERE job.job_id = p_job_id
            LIMIT 1
        ),
        CASE p_destination_type
            WHEN 'direct_role' THEN 'direct'
            ELSE 'discovery'
        END,
        now()
    )
    ON CONFLICT (user_id, client_event_id) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.record_job_apply_intent(text, uuid, text, text)
    FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_job_apply_intent(text, uuid, text, text)
    TO authenticated;

COMMENT ON TABLE public.job_apply_intents IS
    'Durable outbound apply attempts. A row never implies submission.';

NOTIFY pgrst, 'reload schema';
