-- Practice Saves: a user-curated queue of skills to practice in Forge.
-- Skills collected from anywhere on the site (gap session, market, skills page)
-- land here, then surface as their own group on the Practice/Forge page.
-- Mirrors the followed_companies pattern: own-row RLS, upsert-ignore-dupes.
CREATE TABLE IF NOT EXISTS public.practice_saves (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    -- == skills.taxonomy_key (Lightcast L3 name). Not FK-constrained: taxonomy_key
    -- carries no unique index and job_skills resolves the same way (app-side).
    skill_key  TEXT NOT NULL,
    -- denormalised label so the queue renders without a skills join
    display_name TEXT NOT NULL,
    source     TEXT NOT NULL DEFAULT 'gap_session'
               CHECK (source IN ('gap_session', 'market', 'skills', 'job_detail', 'manual', 'other')),
    saved_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, skill_key)
);

CREATE INDEX IF NOT EXISTS idx_practice_saves_user_saved
    ON public.practice_saves (user_id, saved_at DESC);

ALTER TABLE public.practice_saves ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY practice_saves_own_select
        ON public.practice_saves
        FOR SELECT
        USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY practice_saves_own_insert
        ON public.practice_saves
        FOR INSERT
        WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY practice_saves_own_delete
        ON public.practice_saves
        FOR DELETE
        USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT SELECT, INSERT, DELETE ON public.practice_saves TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.practice_saves_id_seq TO authenticated, service_role;
COMMENT ON TABLE public.practice_saves IS
    'User-curated queue of skills to practice in Forge, collected from across the site.';
