from app.schemas.auth import (
    AuthResponse as AuthResponse,
    ExtensionSessionResponse as ExtensionSessionResponse,
    IntegrationRevokeResponse as IntegrationRevokeResponse,
    LoginRequest as LoginRequest,
    MagicLinkRequest as MagicLinkRequest,
    MagicLinkResponse as MagicLinkResponse,
    PostSigninRequest as PostSigninRequest,
    PostSigninResponse as PostSigninResponse,
    RefreshRequest as RefreshRequest,
    RefreshResponse as RefreshResponse,
    SignupRequest as SignupRequest,
)
from app.schemas.cv import (
    CVEvidenceSummaryResponse,
    CVUploadAcceptedResponse,
    CVUploadDoneResponse,
    CVUploadFailedResponse,
    CVUploadResponse,
    CVUploadStatusResponse,
)
from app.schemas.diary import (
    CartSkillSnapshot,
    DiaryEntryRequest,
    DiaryEntryResponse,
    DiaryHistoryResponse,
    MilestoneListResponse,
    MilestoneRequest,
    MilestoneResponse,
    SkillDeltaItem,
)
from app.schemas.xp import (
    XPBalanceResponse,
    XPSpendRequest,
)
from app.schemas.jobs import (
    APPLICATION_STAGES,
    APPLICATION_OUTCOMES,
    APPLICATION_STATUSES,
    ApplicationResponse,
    ApplyIntentRequest,
    ApplicationReviewRequest,
    ApplicationReviewResponse,
    CollectionSnoozeRequest,
    ApplicationStatusUpdate,
    CVBadge,
    CompanyJobCardItem,
    CompanyJobsResponse,
    CompanyPageResponse,
    CompanyReviewItem,
    PostingNoteItem,
    EmergingSkillInput,
    RefreshPreflightResponse,
    RefreshStateResponse,
    RefreshTicketResponse,
    JobFileExtractResponse,
    JobImportPreviewRequest,
    JobImportPreviewResponse,
    JobImportRequest,
    JobImportedDetailsResponse,
    JobImportedDetailsUpdate,
    JobUrlExtractRequest,
    JobPathMilestoneResponse,
    JobPathMilestoneUpdate,
    JobPathResponse,
    JobPathSkillTarget,
    JobPathTargetInput,
    JobPathTargetsRequest,
    JobMatchesResponse,
    JobMatchResponse,
    MatchEval,
    AgentPickItem,
    AgentPicksResponse,
    JobSearchItem,
    JobSearchResponse,
    CompanyOpenRoleItem,
    CompanyOpenRolesResponse,
    CompanyHiringItem,
    TopCompaniesAtResponse,
    GlobalJobHit,
    GlobalJobSearchResponse,
    AnalyticsSnapshotRefreshResponse,
    EntitySkillsResponse,
    MarketAnalyticsResponse,
    MarketAnalyticsSummaryResponse,
    NameCountItem,
    SkillSuggestion,
    SkillCountItem,
    SkillGapItem,
    SkillGapResponse,
    StaleApplicationItem,
    UserSkillDemandItem,
    UserSkillDemandResponse,
)
from app.schemas.scores import (
    ComputeScoreResponse,
    GapSkillResponse,
    MirrorScoreResponse,
)
from app.schemas.skills import (
    SkillResponse,
    SkillsListResponse,
)
from app.schemas.users import (
    FollowCompanyRequest,
    FollowedCompaniesResponse,
    FollowedCompany,
    PracticeSave,
    PracticeSavesResponse,
    SavePracticeSkillRequest,
    SkillUpvoteItem,
    SkillUpvotesResponse,
    SkillUpvoteToggleRequest,
    SkillUpvoteToggleResponse,
    UpdateProfileRequest,
    UpdateProfileResponse,
    UserProfileResponse,
    UserSkillItem,
    UserSkillsByDomainResponse,
)
from app.schemas.profile import (
    JobOverlapResponse,
    JobOverlapRow,
    PublicProfile,
    SuggestNinjaNameResponse,
    UpdateNinjaNameRequest,
    UpdateNinjaNameResponse,
)

__all__ = [
    "SignupRequest", "LoginRequest", "AuthResponse", "RefreshRequest", "RefreshResponse",
    "ExtensionSessionResponse",
    "CVUploadResponse", "CVUploadAcceptedResponse", "CVUploadDoneResponse", "CVUploadFailedResponse",
    "CVUploadStatusResponse", "CVEvidenceSummaryResponse",
    "CartSkillSnapshot", "DiaryEntryRequest", "DiaryEntryResponse", "DiaryHistoryResponse",
    "MilestoneRequest", "MilestoneResponse", "MilestoneListResponse", "SkillDeltaItem",
    "XPBalanceResponse", "XPSpendRequest",
    "APPLICATION_STAGES", "APPLICATION_OUTCOMES", "APPLICATION_STATUSES",
    "JobMatchResponse", "JobMatchesResponse", "MatchEval",
    "AgentPickItem", "AgentPicksResponse",
    "ApplicationStatusUpdate", "CollectionSnoozeRequest", "ApplicationResponse", "ApplyIntentRequest", "ApplicationReviewRequest", "ApplicationReviewResponse", "CVBadge",
    "CompanyJobCardItem", "CompanyJobsResponse",
    "CompanyPageResponse", "CompanyReviewItem", "PostingNoteItem", "StaleApplicationItem",
    "RefreshTicketResponse", "RefreshPreflightResponse", "RefreshStateResponse",
    "JobPathTargetInput", "JobPathTargetsRequest", "JobPathSkillTarget",
    "JobPathMilestoneUpdate", "JobPathMilestoneResponse", "JobPathResponse",
    "EmergingSkillInput", "JobFileExtractResponse", "JobImportPreviewRequest", "JobImportPreviewResponse", "JobImportRequest", "JobImportedDetailsResponse", "JobImportedDetailsUpdate", "JobUrlExtractRequest",
    "EntitySkillsResponse", "MarketAnalyticsResponse", "MarketAnalyticsSummaryResponse",
    "NameCountItem", "SkillSuggestion", "SkillCountItem",
    "JobSearchItem", "JobSearchResponse",
    "CompanyOpenRoleItem", "CompanyOpenRolesResponse",
    "CompanyHiringItem", "TopCompaniesAtResponse",
    "GlobalJobHit", "GlobalJobSearchResponse", "AnalyticsSnapshotRefreshResponse",
    "SkillGapItem", "SkillGapResponse",
    "UserSkillDemandItem", "UserSkillDemandResponse",
    "GapSkillResponse", "MirrorScoreResponse", "ComputeScoreResponse",
    "SkillResponse", "SkillsListResponse",
    "UpdateProfileRequest", "UpdateProfileResponse", "UserProfileResponse",
    "UserSkillItem", "UserSkillsByDomainResponse",
    "FollowCompanyRequest", "FollowedCompany", "FollowedCompaniesResponse",
    "SavePracticeSkillRequest", "PracticeSave", "PracticeSavesResponse",
    "SkillUpvoteToggleRequest", "SkillUpvoteItem", "SkillUpvotesResponse",
    "SkillUpvoteToggleResponse",
    "PublicProfile", "JobOverlapRow", "JobOverlapResponse",
    "UpdateNinjaNameRequest", "UpdateNinjaNameResponse", "SuggestNinjaNameResponse",
]
