from app.schemas.auth import (
    AuthResponse as AuthResponse,
    IntegrationRevokeResponse as IntegrationRevokeResponse,
    LoginRequest as LoginRequest,
    MagicLinkRequest as MagicLinkRequest,
    MagicLinkResponse as MagicLinkResponse,
    PostSigninRequest as PostSigninRequest,
    PostSigninResponse as PostSigninResponse,
    RefreshRequest as RefreshRequest,
    RefreshResponse as RefreshResponse,
    SignupRequest as SignupRequest,
)
from app.schemas.cv import (
    CVEvidenceSummaryResponse,
    CVUploadAcceptedResponse,
    CVUploadDoneResponse,
    CVUploadResponse,
    CVUploadStatusResponse,
)
from app.schemas.diary import (
    CartSkillSnapshot,
    DiaryEntryRequest,
    DiaryEntryResponse,
    DiaryHistoryResponse,
    MilestoneListResponse,
    MilestoneRequest,
    MilestoneResponse,
    SkillDeltaItem,
)
from app.schemas.xp import (
    ForgeCompleteRequest,
    ForgeSessionResponse,
    XPBalanceResponse,
    XPSpendRequest,
)
from app.schemas.jobs import (
    APPLICATION_STAGES,
    APPLICATION_OUTCOMES,
    APPLICATION_STATUSES,
    ApplicationResponse,
    ApplicationReviewRequest,
    ApplicationReviewResponse,
    ApplicationStatusUpdate,
    CVBadge,
    CompanyJobCardItem,
    CompanyJobsResponse,
    CompanyPageResponse,
    CompanyReviewItem,
    EmergingSkillInput,
    RefreshStateResponse,
    RefreshTicketResponse,
    JobFileExtractResponse,
    JobImportPreviewRequest,
    JobImportPreviewResponse,
    JobImportRequest,
    JobPathMilestoneResponse,
    JobPathMilestoneUpdate,
    JobPathResponse,
    JobPathSkillTarget,
    JobPathTargetInput,
    JobPathTargetsRequest,
    JobMatchesResponse,
    JobMatchResponse,
    JobSearchItem,
    JobSearchResponse,
    CompanyOpenRoleItem,
    CompanyOpenRolesResponse,
    GlobalJobHit,
    GlobalJobSearchResponse,
    AnalyticsSnapshotRefreshResponse,
    EntitySkillsResponse,
    MarketAnalyticsResponse,
    MarketAnalyticsSummaryResponse,
    NameCountItem,
    SkillSuggestion,
    SkillCountItem,
    SkillGapItem,
    SkillGapResponse,
    StaleApplicationItem,
    UserSkillDemandItem,
    UserSkillDemandResponse,
)
from app.schemas.scores import (
    ComputeScoreResponse,
    GapSkillResponse,
    MirrorScoreResponse,
)
from app.schemas.skills import (
    SkillResponse,
    SkillsListResponse,
)
from app.schemas.users import (
    FollowCompanyRequest,
    FollowedCompaniesResponse,
    FollowedCompany,
    SkillAdviceRequest,
    SkillAdviceResponse,
    SkillLevelCorrectionRequest,
    SkillLevelCorrectionResponse,
    UpdateProfileRequest,
    UpdateProfileResponse,
    UserProfileResponse,
    UserSkillItem,
    UserSkillsByDomainResponse,
)
from app.schemas.profile import (
    JobOverlapResponse,
    JobOverlapRow,
    PublicProfile,
    SuggestNinjaNameResponse,
    UpdateNinjaNameRequest,
    UpdateNinjaNameResponse,
)

__all__ = [
    "SignupRequest", "LoginRequest", "AuthResponse", "RefreshRequest", "RefreshResponse",
    "CVUploadResponse", "CVUploadAcceptedResponse", "CVUploadDoneResponse",
    "CVUploadStatusResponse", "CVEvidenceSummaryResponse",
    "CartSkillSnapshot", "DiaryEntryRequest", "DiaryEntryResponse", "DiaryHistoryResponse",
    "MilestoneRequest", "MilestoneResponse", "MilestoneListResponse", "SkillDeltaItem",
    "XPBalanceResponse", "XPSpendRequest", "ForgeCompleteRequest", "ForgeSessionResponse",
    "APPLICATION_STAGES", "APPLICATION_OUTCOMES", "APPLICATION_STATUSES",
    "JobMatchResponse", "JobMatchesResponse",
    "ApplicationStatusUpdate", "ApplicationResponse", "ApplicationReviewRequest", "ApplicationReviewResponse", "CVBadge",
    "CompanyJobCardItem", "CompanyJobsResponse",
    "CompanyPageResponse", "CompanyReviewItem", "StaleApplicationItem",
    "RefreshTicketResponse", "RefreshStateResponse",
    "JobPathTargetInput", "JobPathTargetsRequest", "JobPathSkillTarget",
    "JobPathMilestoneUpdate", "JobPathMilestoneResponse", "JobPathResponse",
    "EmergingSkillInput", "JobFileExtractResponse", "JobImportPreviewRequest", "JobImportPreviewResponse", "JobImportRequest",
    "EntitySkillsResponse", "MarketAnalyticsResponse", "MarketAnalyticsSummaryResponse",
    "NameCountItem", "SkillSuggestion", "SkillCountItem",
    "JobSearchItem", "JobSearchResponse",
    "CompanyOpenRoleItem", "CompanyOpenRolesResponse",
    "GlobalJobHit", "GlobalJobSearchResponse", "AnalyticsSnapshotRefreshResponse",
    "SkillGapItem", "SkillGapResponse",
    "UserSkillDemandItem", "UserSkillDemandResponse",
    "GapSkillResponse", "MirrorScoreResponse", "ComputeScoreResponse",
    "SkillResponse", "SkillsListResponse",
    "UpdateProfileRequest", "UpdateProfileResponse", "UserProfileResponse",
    "UserSkillItem", "UserSkillsByDomainResponse",
    "SkillAdviceRequest", "SkillAdviceResponse",
    "SkillLevelCorrectionRequest", "SkillLevelCorrectionResponse",
    "FollowCompanyRequest", "FollowedCompany", "FollowedCompaniesResponse",
    "PublicProfile", "JobOverlapRow", "JobOverlapResponse",
    "UpdateNinjaNameRequest", "UpdateNinjaNameResponse", "SuggestNinjaNameResponse",
]
